### ISSUE TITLE
autocomplete item not clickable on mobile devices

### ISSUE THREAD

**Issue by al-eax** [anvilistas/anvil-extras#103]
Hi anvil community,

I use the Autocomplete in my app and i have problems to get it working on mobile devices.
On mobile devices I was not able to select a suggested item by clicking or pressing enter:

![grafik](https://user-images.githubusercontent.com/2324292/124327569-6915be80-db88-11eb-9173-908d6306e1a6.png)

I tested this on Galaxy S8 and Iphone 6S.

Open this sample app on your mobile device and type "A":
https://AUSGIWLXDFGUKBDZ.anvil.app/RAPVVK5WB4R3KSLG2ENC3JCV
or clone the app:
https://anvil.works/build#clone:AUSGIWLXDFGUKBDZ=YAB7DUIKKSQTEC2MWDS3R36C

**Comment by s-cork** [comment]
Thanks for reporting.

**Comment by al-eax** [comment]
@s-cork thank you for your fast response and fix. I switched the dependency to develop in the sample app, to get you patch. Unfortunately it still takes 10 to 20 clicks until the item gets selected.

**Comment by meatballs** [comment]
That fix hasn't been released to the main app, so you won't yet have it available. I'll get that done when I'm back at my computer on Monday.
