### ISSUE TITLE
Curiosity: How you replaced the default form template for AutoComplete Component in Anvil Eidtor?

### ISSUE THREAD

**Issue by Stevenlimo** [anvilistas/anvil-extras#107]
Hi Stu/Owen, 
In your documentation https://anvil-extras.readthedocs.io/en/latest/guides/components/autocomplete.html

You state: A material design TextBox with autocomplete. A subclass of TextBox - other properties, events and methods inherited from TextBox.

As a result, the following template is implemented for the AutoComplete Form 
https://github.com/anvilistas/anvil-extras/blob/main/client_code/Autocomplete/form_template.yaml

As far as I know, I don't see any way that we can change the default form template like above in the Anvil Online Editor. How exactly did you do it for the AutoComplete Component? It would be great if you could share your know-how so that we can create our own form template at desire. 

Thanks in advance 
Steven

**Comment by s-cork** [comment]
I changed it manually - i.e. checked the code out in git locally, edited the yaml, and pushed it back to anvil.
It's a total hack!
But there's nothing special about the container type. Its only job is to determine the base class for the `FormTemplate`.

**Comment by Stevenlimo** [comment]
Amazing. I haven't used GitHub yet but it is good to know GitHub can push codes back to Anvil. I am still learning about Anvil at my spare time. Thank you for sharing.

**Comment by s-cork** [comment]
Not github - just git. (Github uses git and so does anvil). 
"Checking out the code locally with git" just means editing it in a local code editor.

Anvil docs on git: https://anvil.works/docs/version-control/git

**Comment by Stevenlimo** [comment]
Thank you Stu, I am going to have a read on that. Thank you for all the good work.
