### ISSUE TITLE
Contributing guide: issue linking

### ISSUE THREAD

**Issue by hugetim** [anvilistas/anvil-extras#126]
[This text](https://anvil-extras.readthedocs.io/en/latest/guides/contributing.html#issues) continues to puzzle me:

> If you could start the name of the branch you work on with the number of the issue you create, that would be very helpful as github will automatically link the two together.

If this is true, can you add an example or link to more detailed instructions? All I can find when I search for this is instructions that instead say to put something like "Resolves #ISSUE" in the pull request description: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by meatballs** [comment]
Yeah, I think we can dump that. (The whole document is copied from a past project and I don't think that bit is necessary any more).
