### ISSUE TITLE
Storage - IndexedDB storage

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#130]
localStorage is good for some things but it's fairly limited.
We might consider a wrapper for IndexedDB.

There are plenty of good javascript wrappers already out there.
https://github.com/localForage/localForage
or 
https://github.com/dannyconnell/localbase

So we could wrap a wrapper?

**Comment by hugetim** [comment]
I'd like to see this functionality become part of Anvil proper, after the kinks are worked out.
