### ISSUE TITLE
Background Sync Capability

### ISSUE THREAD

**Issue by rhurlbatt** [anvilistas/anvil-extras#141]
Saving large amounts of data to IndexedDB will likely require some kind of background sync functionality to avoid having to keep the app open to save the data to the data tables service when a connection is available.

Currently I think only Chromium and Edge browsers support the Background Sync API but it appears iOS will be adding support for this (hopefully soon).

I am just dreaming here but could this functionality be added in to anvil_extras until Anvil implements this sort of functionality?

**Comment by s-cork** [comment]
I think it's an interesting idea, but I think it's a case of this won't be added any time soon.

If you'd like to pick this up @rhurlbatt let us know.
Otherwise I'm closing the issue for now and tagging as wont fix
