### ISSUE TITLE
Multiselect dropdown remains visible

### ISSUE THREAD

**Issue by hugetim** [anvilistas/anvil-extras#144]
If it is not specifically dismissed, the multiselect dropdown remains visible after the underlying form is hidden:
![MultiSelect Bug](https://user-images.githubusercontent.com/8237868/133686852-09b191f3-1b49-4eaf-a8ab-2c84d35eec1b.gif)

**Comment by s-cork** [comment]
well that is terrible - do you want to have a look at this @hugetim - probably can be fixed by adding an event to the hide event

**Comment by hugetim** [comment]
Ack, I've spent some hours on this, but I'm having trouble.

Here's what I have so far:

1. Whether the dropdown menu is shown can be tracked using the [bootstrap-select events](https://developer.snapappointments.com/bootstrap-select/options/#events) "shown.bs.select" and "hidden.bs.select".
2. If the dropdown menu is shown, it can be hidden with the [bootstrap-select method](https://developer.snapappointments.com/bootstrap-select/methods/) `.selectpicker("toggle")`
3. However, the `hide` event on the HTMLTemplate doesn't seem to be working. ([And this seems to be a more general Anvil issue.](https://anvil.works/forum/t/hide-event-not-working/9821/2)) So I'm at a loss as to how to check when to manually toggle the dropdown menu (if shown at the time).
