### ISSUE TITLE
Autocomplete suggestions not showing up when used in a popover window

### ISSUE THREAD

**Issue by ethanedson** [anvilistas/anvil-extras#148]
When I use an autocomplete widget within a popover form, the suggestions don't appear in view like they normally would.  Thanks for having a look!

**Comment by s-cork** [comment]
could you provide a clone link. It'll make it much easier to implement a fix.

**Comment by ethanedson** [comment]
Here is a clone link: https://anvil.works/build#clone:WZQMOXTO6FI3GKXS=6CYOQON4CJYUG4J6JA5RMSB6

**Comment by s-cork** [comment]
Thanks. I have a fix now. You'll see it in the next release. (There's a linked pr above if you want to see the code changes)
