### ISSUE TITLE
MultiSelectDropdown issue with anvil app server

### ISSUE THREAD

**Issue by sebasm611** [anvilistas/anvil-extras#156]
Hi! I'm not sure if the issue should be posted here or under the anvil-runtime repo.

I'm trying to deploy an app on AWS and when I run it it's giving me this error:

`[ERROR anvil.app-server.run] Error report from client code:
AttributeError: module 'js' has no attribute 'await_promise'
Traceback:
  app/anvil_extras/utils/_component_helpers.py:56

  app/anvil_extras/MultiSelectDropDown/__init__.py:32

  app/gen_propuestas_anvil/Home/__init__.py:18`

The first component that loads from anvil-extras es precisely a MultiSelectDropDown so I'm not sure if the issue is with all the widgets.

Any ideas on how should I go about fixing this error?

Thanks in advance!

**Comment by s-cork** [comment]
The app server is usually behind anvil.works in terms of features.

It's best to make this request on either the main forum or the app-server's GitHub and request an update. 

For now you can use anvil-extras before version 1.6 which won't include that feature.

**Comment by sebasm611** [comment]
Thanks! v1.5.2 worked
