### ISSUE TITLE
Some anvil_extras features not working on local app environment

### ISSUE THREAD

**Issue by Stevenlimo** [anvilistas/anvil-extras#163]
For my learning purpose, I did an anvil_extras test on the anvil local app server, and I've found that some anvil_extras features such as slider and storage are not working due to the missing of "anvil.js.import_from' on the local app server.  Then I did a comparison of 'dir' on the two environments: 

dir(anvil.js) on the online IDE shows:
['ExternalError', '__name__', 'await_promise', 'call', 'call_js', 'get_dom_node', 'import_from', 'new', 'report_exceptions', 'to_media', 'window']

dir(anvil.js) on the local app virtual environment shows: 
['ProxyType', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'anvil']

Therefore, I assume that any anvil_extras features come with ['await_promise', 'call', 'call_js', 'get_dom_node', 'import_from', 'new', 'report_exceptions', 'to_media', 'window'] will not work on the local python virtual environment. 

Will this anvil.js module on the local app server get updated soon? Or can anvil_extras features be written in a way  without using the above missing functions?

**Comment by s-cork** [comment]
Yes the app server is usually behind the anvil.works environment. Use a version of anvil-extras before 1.6.0 and it should be ok.
