### ISSUE TITLE
Select all / deselect all toggle - multiselect dropdown 

### ISSUE THREAD

**Issue by RedOchrePM** [anvilistas/anvil-extras#189]
It would be useful to be able to toggle all-on / all-off, especially for long dropdown lists:

![2021-10-21_18-59-56](https://user-images.githubusercontent.com/71299741/138265073-603d958c-9dc7-4011-a17e-9c88d787a206.png)

**Comment by s-cork** [comment]
Do you fancy writing the pr?
It's a fairly easy implementation.
(Approximately 4 lines of code)

https://developer.snapappointments.com/bootstrap-select/methods/

You just have to hook into the api above with a `select_all` and `deselect_all` method in anvil.
You can see this working with the unsupported api.
```python
self.multil_selecet_drop_down._el.selectpicker("selectAll")
```
