### ISSUE TITLE
Serialisation module on the free plan

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#212]
**Describe the bug**
At the moment the development branch breaks free user accounts for server calls
All server modules are loaded on a server call including the serialisation module
On the free plan marshmallow is not available which will throw an error

**To Reproduce**
- depend on the development branch
- switch to python basic 
- call a server function

**Additional context**
We should probably lazy load marshmallow anyway for performance reasons.
(given that the serialisation module will be imported for each server call)

**I am considering making a PR for this issue**
Assuming @meatballs will want to take this.

**Comment by meatballs** [comment]
I can't get to this for a few days.

**Comment by s-cork** [comment]
Sure. I can commit something that fixes it later and you can tidy it up when you get a chance?

**Comment by meatballs** [comment]
Sure. A getattr fix, I assume?

**Comment by s-cork** [comment]
Yeah I was thinking a lazy module that we can import marshmallow from lazily. Then use that for future similar use cases. 

```python 
import lazy_module_loader as lazy 

...
    lazy.marshmallow 
```
