### ISSUE TITLE
MultiSelect dropdown

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#23]
It would be good to do this well

**Comment by s-cork** [comment]
This looks promising as providing a jquery api:
https://github.com/davidstutz/bootstrap-multiselect

We would then need to decide on what api to expose in the component.
I think we'd want to do something similar to the dropdown and have `self.items` being a list of strings or a list of tuples
Then we'd also want to think about exposing `groups`  so maybe `self.items` could also be a dict where each key is a group... and each value is a list of strings or tuples... relying on python dictionaries being ordered.

I guess we'd also have the `selected_values` api which always returns a list, (or a tuple 🤔) and can be set to an iterable of values.

**Comment by s-cork** [comment]
I'm currently working on this.

What do you think about this as an api for the items property?

```python
self.multi_dropdown.items = ['a', 'b', 'c'] # list of strings
self.multi_dropdown.items = [('a', 1), ('b', 2), ('c', 3)] # list of (str, value) tuples

# list of dicts with the following attributes: key, value, tooltip, enabled, selected
self.multi_dropdown.items = [{'key': 'a', 'value': 1, 'tooltip': 'A', 'enabled': True, 'selected': True}, {'key': 'b', 'value': 2}]


# include a divider
self.multi_dropdown.items = ['a', 'b', '---', 'c'] # use --- anywhere you want a divider
# include groups
self.multi_dropdown.items = ['group 1', '  1.1', '  1.2', '  1.3', 'group 2', '  2.1', '  2.2'] # use indentation with a list of strings
self.multi_dropdown.items = [{'group': 'group 1', 'options': ['1.1', '1.2', '1.3']}, {'group': 'group 2', 'options': ['2.1', '2.2']} ] 

```

**Comment by meatballs** [comment]
That looks very nice! I particularly like the inclusion of the divider.

**Comment by s-cork** [comment]
This is currently where i'm at - https://anvil.works/build#clone:YUAZWZ55TECOMZNQ=SVETDNR5WFTSYZDOWINRKDGL

Annoyingly that library was using bootstrap 3 in v0.9.15 (anvil uses bootstrap 3) and they switched to bootstrap 4 in v1.0.0.

If you have 5 minutes maybe you can see what you think.
For now I've not included groups

**Comment by meatballs** [comment]
That looks like it's working nicely. Is it deliberate or just a typo that the class is 'MultSelect' rather than 'MultiSelect'?

**Comment by s-cork** [comment]
always a typo

**Comment by hugetim** [comment]
It looks like this library ended up being used rather than the 'bootstrap-multiselect' linked to above: https://github.com/snapappointments/bootstrap-select/

**Comment by s-cork** [comment]
Correct. Can't remember the reason. I think the API was nicer or they were prettier or both.
