### ISSUE TITLE
Possible bug in routing.set_url_hash when load_from_cache=False

### ISSUE THREAD

**Issue by jshaffstall** [anvilistas/anvil-extras#243]
I use code like this as part of my login sequence:

```
      anvil.users.login_with_form(allow_cancel=True)
      routing.set_url_hash(self.tag, load_from_cache=False, replace_current_url=True) 
```

The problem comes when the form the user is currently on is the same one referenced by self.tag.  Given that I'm passing load_from_cache=False, I expected the form to be reloaded, with new calls to init and form_show.  

Instead the form simply remained visible, with no calls to any function on the form.

The following code fixed the issue and caused the behavior I expected:

```
      anvil.users.login_with_form(allow_cancel=True)
      routing.remove_from_cache(self.tag)
      routing.set_url_hash(self.tag, load_from_cache=False, replace_current_url=True) 
```

Posting here in case this is a bug in the routing library that needs addressed.

**Comment by s-cork** [comment]
Did you want to make a pr for this? It's line 518 in `_routing.py`.

**Comment by jshaffstall** [comment]
I added a pull request for something I think will work.  I do not have an app setup to test a custom version of Anvil Extras, though, so check over the logic to make sure I'm not missing something obvious.
