### ISSUE TITLE
Please provide slider styling options

### ISSUE THREAD

**Issue by mjmare** [anvilistas/anvil-extras#258]
I was happy that a slider was included in the Anvil Extras library. Being based on noUIslider it provides nice functionality. 
However the visual appearance is huge and far less sophisticated than the original.
Is CSS styling the only way to style?
Please provide a way to select an alternative style from the IDE if possible. TIA.

**Comment by meatballs** [comment]
Are you planning to submit  pull request for this?

**Comment by mjmare** [comment]
No, wouldn't know how. Looking at the source code I see all kinds of unfamiliar magic.

**Comment by s-cork** [comment]
Can you provide examples of the styling you're after? (Writing magic code is one thing but mind reading isn't something we've mastered yet 🧙‍♀️). 

To me this seems like a roles request and if that's the case we can help with the type of css role you'd need to write and then document it.

**Comment by s-cork** [comment]
We added styling in version 1.9.0 - namely thickness and handle_size which should address the initial request here

We also added a role property so that things like the handle can be styled in theme.css

noUiSlider has some examples of styling where a role would be appropriate
