### ISSUE TITLE
ExternalError: SyntaxError: the import keyword may only appear in a module at app/anvil_extras/storage.py, line 14

### ISSUE THREAD

**Issue by stenci** [anvilistas/anvil-extras#260]
See [this forum post](https://anvil.works/forum/t/anvil-extras-externalerror-syntaxerror-the-import-keyword-may-only-appear-in-a-module-at-app-anvil-extras-storage-py-line-14/11289).

**Describe the bug**
An app shows this error, only on Firefox, only on one computer:
```
ExternalError: SyntaxError: the import keyword may only appear in a module at app/anvil_extras/storage.py, line 14
```

I am reporting this before any deep exploration because (1) I'm afraid to see it spreading to more computers, or (2) some changes have been made to the dependencies that have broken it.

**To Reproduce**
I don't know how to reproduce it. 
It works on my computer both with Chrome and Firefox, it works on a second computer on Chrome, the problem reproduces on that computer on Firefox.
I pressed Ctrl+F5 to force a refresh, but nothing changed.

**Screenshots**
![image](https://user-images.githubusercontent.com/5955495/151068381-0c9feb4f-5082-44fe-9d00-134d26adcae6.png)

Line 14 doesn't even have an `import`.

Any idea what's going on?

It is not a big deal, it's an app for internal use, so I can tell the user to use Chrome. 
But this is not the most elegant solution.

Now I will try to explore and see if I can figure out something.

**Comment by stenci** [comment]
Updating Firefox fixed the problem

**Comment by s-cork** [comment]
Version wise Firefox 67+ should be fine. Which looks like it was released in May 2019.
