### ISSUE TITLE
MultiSelect not losing focus if the next click is on a button

### ISSUE THREAD

**Issue by rhurlbatt** [anvilistas/anvil-extras#271]
**Describe the bug**
As per this [link](https://ORD2UN3EYHQNQM4J.anvil.app/U3ESYAG33FP6SDTOUJNOYP22), if you have the multiselect's items menuopen and you click on a button, the multiselect does not close.

If the click is on the background of the form, then the menu closes correctly.

**To Reproduce**
See this [link](https://ORD2UN3EYHQNQM4J.anvil.app/U3ESYAG33FP6SDTOUJNOYP22)
[Clone Link](https://anvil.works/build#clone:ORD2UN3EYHQNQM4J=FNGGKWOX5UNKYOS4PDQMSOWF|C6ZZPAPN4YYF5NVJ=)

**Expected behavior**
If the click is on the button, the menu should close.

**Screenshots**
![image](https://user-images.githubusercontent.com/31876600/153800385-1b6af600-37e2-4fe0-b8a5-a9b59317af39.png)

**Additional context**
None

**I am considering making a PR for this issue**
Yes

**Comment by s-cork** [comment]
Hey @rhurlbatt I didn't notice you'd considered writing a PR.

I've done that now.
It was a bit of a nightmare to fix so probably best not to have taken this one on.

**Comment by rhurlbatt** [comment]
Thanks Stu - no worries, I hadn't got very far at all to be honest.
 I appreciate the quick support. I will spend some time on the code and get
my head around the solution.

Thanks again for your help.
