### ISSUE TITLE
Quill set_html_dangerously(html)

### ISSUE THREAD

**Issue by steininge** [anvilistas/anvil-extras#273]
The Quill editor allows you to include images which are returned in the html string as <img src="data:image/png;base64, ...>. 

When you set such an html string to a quill, the image is dropped because the html has been sanitized into safe html.

**Describe the solution you'd like**

Could we include a method that does not sanitize the html, and thus keeps the images?

```
def set_html_dangerously(self, html):
        """set the content to html, with no conversion to safe html """
        self._quill.root.innerHTML = html
```

**I am considering making a PR for this issue**
If you agree to the change, I was hoping you could just paste the code as-is or edited, and we could avoid the PR, if that's ok.

**Comment by s-cork** [comment]
Sure. Though I'm not sure I 
 like that api. 

How about amending the `set_html()` method to include a `sanitize=True` keyword.

**Comment by steininge** [comment]
Yes, that's a much better idea.

Thanks!

**Comment by s-cork** [comment]
And just as an idea. There could also be a sanitize bool property passed to the init method. 

This could be the default sanitize option (as true). So the kwarg would be `set_html(self, html, sanitize=None)`. Then if it's None use the `self._props['santize']` value instead. 

This might make it more convenient for anyone using the component who never wants the html sanitising whilst keeping the current behaviour as the default. 

Just a suggestion - looking forward to the PR.

**Comment by s-cork** [comment]
Ah missed the comment about the PR. Shouldn't take me long to knock something up.

**Comment by steininge** [comment]
Thanks Stu, for creating the PR!

I realize I should've created the PR myself instead of burdening you with the extra work. Sorry about that, I'll do it right next time.
