### ISSUE TITLE
Scrolling inside Popovers

### ISSUE THREAD

**Issue by GDuroS** [anvilistas/anvil-extras#275]
I imported the popover module from anvil-extras (using the published version of the dependency) in one of my forms.
The content of the popover is another component which has a few other components. The last one is a type of accordion component that uses the animation module to show / hide a description for each title.

Since the total height of this last component is too huge for the popover, I manually set the height of the component to fit the popover with the intention that the user would be able to scroll **inside** the popover that specific component.

Looking in the docs, it's mentioned that to allow behaviors like the one I mentioned I need to create a container for the popover and set it using the prop "container" or the method `set_default_container`, however none of those are available in the module / method.

![image](https://user-images.githubusercontent.com/92797711/155857662-e3992e8c-836d-47f0-8bb8-6054b314c720.png)
![image](https://user-images.githubusercontent.com/92797711/155857713-bba1e525-52cc-41d8-896d-a51ac99d2669.png)
![image](https://user-images.githubusercontent.com/92797711/155857725-600329eb-8b71-4851-b3cd-5ad59be7ced8.png)

Am I doing something wrong? Is this option deprecated? Or is there any other way of doing this, since every time I try to scroll inside of the popover (even if trying to use the bars) the popover is dismissing (which I know it's intended).

**Comment by GDuroS** [comment]
You can demonstrate using my development link:
[Anvil Link](https://ahzi2fa2xmm3jk5v.anvil.app/H5DMY45QP2Q5JS5AJYBKJYNE)

And doing the following steps (the app is in portuguese, so I'll guide step by step) after the app is loaded (it's going to open specifically in the right page, logged with a dummy user):
![image](https://user-images.githubusercontent.com/92797711/155861467-097b7f0d-b2c9-4ef0-8799-59f2d68782a5.png)
Type 1 in the marked field to filter only one item and then click on the marked button to filter.

A few seconds later a card will appear in the bottom area of the screen:
![image](https://user-images.githubusercontent.com/92797711/155861534-0ffd3b4e-6bc3-448a-8c7c-4e5140f6b8c2.png)
Click on the red button of the card. The popover will appear:
![image](https://user-images.githubusercontent.com/92797711/155861552-0e54edc3-c9d7-45dc-862e-990a36bd4fe6.png)
Clicking on any of the buttons in the right-most part of the popover will expand the section with a little description. That makes the section go beyond the height available.
![image](https://user-images.githubusercontent.com/92797711/155861576-25adb11e-1a1e-46f3-bad6-e39af73aa481.png)
What I want is to be able to scroll with or without the bars to see the rest of the text or even to click on the other buttons. However, as soon as I scroll or drag the bars the popover is dismissed.

If you need any other information, let me know. If you absolutely would need a clone link, then I can try to make a clone link isolating the situation.

**Comment by s-cork** [comment]
maybe switch to the development version and see if setting the scroll behaviour works for you.

**Comment by s-cork** [comment]
Just fixed a bug for the behaviour you experienced. Try the development branch again.

**Comment by GDuroS** [comment]
Hi @s-cork. I just tested the development branch and it worked correctly the way I needed even without using the container, popover div or dismiss_on_scroll.

I did try to change to v1.9.0 and it also worked, but since it worked now in the development branch, I'll stay using it.

Thank you!
