### ISSUE TITLE
Problem with published branch

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#277]
**Describe the bug**
Published branch does not point to the 1.9.0 release

**To Reproduce**
```python
from anvil_extras import serialisation
# ImportError
```

**Expected behaviour**
serialisation was part of the latest release so something is up

**Additional context**
flagged in #275 

**I am considering making a PR for this issue**
No

**Comment by hugetim** [comment]
I can confirm this is still an issue. I was still seeing [this bug](https://github.com/anvilistas/anvil-extras/issues/271) when set to the Published branch, but it goes away when I explicitly set the version to 1.9.0 or 2.0.0.

Actually, it may be best to leave the Published branch pointing to 1.9.0 to avoid breaking changes for those with the dependency set to "Published." But then we should just change the [docs](https://github.com/anvilistas/anvil-extras/blob/main/docs/guides/installation.rst#install-as-a-third-party-dependency) to note that.

**Comment by meatballs** [comment]
I'll fix the published branch manually and then add something to the github action to do so from then on.

**Comment by hugetim** [comment]
Last thought: if you're at all considering leaving 'Published' at v1.9.0, you could create a new Published2 branch that updates automatically with new v2.0.x releases.
