### ISSUE TITLE
Add Open and Close Events to MultiSelect Dropdown

### ISSUE THREAD

**Issue by Duncanr-glitch** [anvilistas/anvil-extras#279]
**Is your feature request related to a problem? Please describe.**
There's no way to trigger code when the dropdown is opened/closed. I think the closed event is more important because then the selection of options is complete.

**Describe the solution you'd like**
Custom Events of open and close be added to the component

**I am considering making a PR for this issue**
Yes, PR is coming forthwith

**Comment by s-cork** [comment]
You could try the `'shown.bs.select'` and `'hidden.bs.select'` events - similar to the `'changed.bs.select'` approach.

**Comment by Duncanr-glitch** [comment]
Oh that's much easier than what I had hacked together -- I was hacking together a convoluted implementation of the MutationObserver.

**Comment by s-cork** [comment]
@Duncanr-glitch did you get anywhere with this?
