### ISSUE TITLE
Regression on before_unload

### ISSUE THREAD

**Issue by stenci** [anvilistas/anvil-extras#289]
Some of my apps with the dependency to `anvil_extra` set to `Published` keep asking if I want to save the changes, even on page that don't make or save any changes.

I set the dependency back to the `1.9.0` and I got the correct behavior, that is it would ask to save only if it was supposed to.

I haven't dug much, I don't know what causes the problem. I have the dependency set to your public repository and digging would take me some time, so I thought I would report this problem quickly, before it spreads around too much.

What I have discovered so far is that, after the `before_unload` is fired correctly, it seems to be fired again on a form that doesn't have it.

I have a form that asks you to pick the project you want to edit from a repeating panel, you pick the project and you are sent to another form, you edit, you navigate back to the list of projects without saving and the `before_unload` checks if you have saved or not. Then you pick another project and the `before_unload` is fired again, on the form with the list of projects that doesn't have `before_unload` defined.

I do the navigation back with the browser arrow.
I do the navigation forward, that is when I pick a project I go to the edit form with:
`routing.set_url_hash(url_pattern=self.next_page, url_dict=url_dict, load_from_cache=False)`

**Comment by stenci** [comment]
Here is an app that reproduces the problem: https://anvil.works/build#clone:AGPMESWCPTB6QZ4Z=7HJ3AESPNFTIXNIT7MKEYIN4

The steps to reproduce the correct behavior:

1. Set the dependency version to `1.9.0`
2. Run the app
3. Click on the "show form3" button -> form3 is shown
4. Click on the back arrow -> `before_unload` is executed
5. Click on 'OK' -> form2 is shown
6. Click on the "show form3" button -> form3 is shown

The steps to reproduce the **_problem_**:
1. Set the dependency version to _**`Published`**_
2. Run the app
3. Click on the "show form3" button -> form3 is shown
4. Click on the back arrow -> `before_unload` is executed
5. Click on 'OK' -> form2 is shown
6. Click on the "show form3" button -> _**`before_unload` is executed - wrong**_

**Comment by s-cork** [comment]
Think i've found it @stenci thanks

**Comment by s-cork** [comment]
so @stenci 2.0.1 should now be available for you to test out - i've checked your clone on that version and expected behaviour restored.

**Comment by stenci** [comment]
Thanks for the quick fix.

Is there a way to/are you testing this kind of problems?

I don't. 
I only test the logic, I don't know how to test this little details about how the UI behaves. 
My users are often shop workers, unable to recognize when something goes wrong. So, unless I happen to play with that app as I did today, the misbehavior will be considered normal behavior. And if they click on "Save"... I guess the app will just crash because there is nothing to save, so no big deal.
