### ISSUE TITLE
Possible issue with routing templates

### ISSUE THREAD

**Issue by jshaffstall** [anvilistas/anvil-extras#293]
**Describe the bug**

This may just be my misunderstanding how things should work.  With the new routing template system, the templates are containers for anything matching the template's URL prefix.  

I have two templates:

```
@routing.default_template
class RouterPublic(RouterPublicTemplate):
```

and

```
@routing.template(path="user", priority=1, condition=lambda: Globals.user is not None)
class RouterUser(RouterUserTemplate):
```

The public router includes a form that matches the `''` url pattern, and the user router includes a form that matches the `'user'` pattern.  In my mind those are the home forms for both templates.  

What I'd expected was that if the user not not logged in, the public router would be the template used, and only forms imported in the public router would be able to be shown.  

What I'm seeing is that the public router is shown, but if I modify the URL to go to #user the user home form is shown in the public template.  

This makes sense from a technical perspective, since the routing library has all the forms registered.  But I'd expected the forms to inherit the condition of the enclosing template.  I don't know if that should happen, or is a feature request, or will never happen.

**Comment by s-cork** [comment]
This is expected behaviour - but I agree this should be implemented - we just need an API for it.

Currently templates don't know anything about routes and routes don't know anything about templates.
The question is how do we make them know about each other - (in a backward compatible way)

```python
@routing.template(registered_rotes=[HomeForm, ...])
class RouterPublic(RouterPublicTemplate):

```

Or

```python
@routing.template(path="user", priority=1, routes=[UserHome, ...], condition=lambda: Globals.user is not None)
class RouterUser(RouterUserTemplate):

```

where no registered routes means anything goes...

---

And what about the version where you have say
```python
@routing.template(path="", priority=1, condition=lambda: Globals.user is not None)
class RouterPrivate(RouterPrivateTemplate):

@routing.default_template
class RouterLogin(RouterLoginTemplate):
```

Then you'd want to route forms registered to the same route, one for the RouterLogin and one for the RouterPrivate

This would change the cache structure - since we'd need the keys to be the url_hash plus the template.

---

@jshaffstall any thoughts on the API here?

**Comment by jshaffstall** [comment]
I'd think it's up to the routes to attach themselves to a template.  That way a form could be part of multiple templates depending on the url pattern.  I have an app where I have forms that serve double duty in different sections of the app based on the url pattern.

Maybe something like:

```
@routing.route('account/forms', template='RouterAccount')
@routing.route('admin/forms', template='RouterAdmin')
```

Side question, since the template provides part of the url, would we need to duplicate that in the route? e.g.

```
@routing.template(path="account")
class RouterAccount(RouterAccountTemplate):

```

And a form using that template:

```
@routing.route('forms', template='RouterAccount')
```

The full url would be `account/forms`.  Not sure if that complicates things or makes them easier, or for who.

I agree that caching needs some attention.  If I have a form that registers to multiple templates, there will be times each url pattern should lead to a different instance of the form.

But I can also see situations where it'd be the same form.  In the situation you had above:

```
@routing.template(path="", priority=1, condition=lambda: Globals.user is not None)
class RouterPrivate(RouterPrivateTemplate):

@routing.default_template
class RouterLogin(RouterLoginTemplate):
```

I could see using those two templates to have different sidebar links, but the form instance itself being the same between the two.  In this particular case the url pattern is the same, so if you left the template out of the hash you'd get the behavior I'd tend to expect.  Identical url patterns lead to the same instance of the form, regardless of template.  Different url patterns lead to different instances of the form.

I don't know if that would be counterintuitive for other people, though.

**Comment by s-cork** [comment]
I'll have a play around at some point. See if I can come up with the right thing. 

Any other opinions most welcome. 

I do like the - only put part of the url pattern for route forms when the template already includes the starting path. Might get a bit complicated. 

It might also have to be `templates` rather than `template`. Where it could be a string or iterable of strings. 

I could also just clear the cache on template change. That might be an easy win.

**Comment by jshaffstall** [comment]
Yeah, if the route pattern doesn't need to include what's already in the template, then the route could register to multiple templates for the same pattern with an iterable and have a consistent url hierarchy.  

>I could also just clear the cache on template change. That might be an easy win.

That'd lose any data entered into form fields if they used the back button to go back a different template, which isn't ideal.

What if the cache was based on the route decorator?  (No idea how difficult that would be)  For example:

```
@routing.route('forms', template='RouterAccount')
@routing.route('forms', template='RouterAdmin')
```

Those would be two different form instances in the cache, but:

```
@routing.route('forms', template=['RouterAccount', 'RouterAdmin'])
```

That would be the same form instance showing on two different templates.  That gives the programmer control over which urls go to distinct instances.  Not sure if that would be confusing to most folks, though.
