### ISSUE TITLE
Template argument error with published version

### ISSUE THREAD

**Issue by jshaffstall** [anvilistas/anvil-extras#316]
With the most recent published version of Anvil Extras, I get this error:

```
TypeError: __init__() got an unexpected keyword argument 'template'
```

On this line:

```
@routing.route('', template='RouterPublic')
```

The error does not happen if I switch to the development version, or if I tag v2.1.0 directly, just if I'm on the published version.

**Comment by s-cork** [comment]
Think this requires @meatballs  to do a manual bump of the version

**Comment by meatballs** [comment]
done

**Comment by jshaffstall** [comment]
Works now, thanks!
