### ISSUE TITLE
Fix margin on PageBreak component

### ISSUE THREAD

**Issue by meatballs** [anvilistas/anvil-extras#33]
The margin of -55px taken from the original css doesn't seem to work now that it's incorporated into a form.

Probably best to make it a property so it can be passed in.

**Comment by s-cork** [comment]
Doesn't work means - that it has no effect?

**Comment by meatballs** [comment]
Ah. Sorry, I should have been a little more specific!

It actually works just fine - it moves the next page up by 55 px which brings it back into the prior page! 

Hard setting it to 0px (or just removing the line) makes it all behave nicely.

**Comment by s-cork** [comment]
oh that's interesting - for me I got the opposite - when I added it to the page I had an extra 55px on the current page. Which is why i added it in the first place.

It could be browser/os specific which would be annoying!

**Comment by meatballs** [comment]
> It could be browser/os specific which would be annoying!

It certainly would.

I also can't see a clean way to pass in a property to custom HTML if I also want it to cope with multiple entries on the same form.

This component stuff gets more difficult each time I try it!

**Comment by s-cork** [comment]
you can change `self.html` and use an f string

**Comment by meatballs** [comment]
Yeah, I just thought that was a little dirty and was hoping to come up with something cleaner.

Failing miserably thus far, so that may have to do.
