### ISSUE TITLE
Bug in hashlib module

### ISSUE THREAD

**Issue by ConschiB** [anvilistas/anvil-extras#336]
I tried implementing the hashlib library, with the example in the docs:
<img width="616" alt="image" src="https://user-images.githubusercontent.com/101922816/168278125-7c22f10e-ca86-4a27-8fb8-eea965df35ca.png">

However I received an Error message: TypeError: digest() got multiple values for argument 'algorithm'

When instead importing the module as: "from anvil_extras.hashlib import digest" and directly call the function, everything works fine:
print(digest("SHA-256","Hello World!"))

**Comment by s-cork** [comment]
thanks for reporting, as a temporary work around if you change your code to be

```python
sha256(data="Hello World!")
```
it should work

**Comment by ConschiB** [comment]
Thanks for your response. Yes that work-around works absolutely fine.

**Comment by s-cork** [comment]
@ConschiB it should now be fixed if you switch over to the development branch
