### ISSUE TITLE
Adding url_keys to route decorator is making the route stop working at all

### ISSUE THREAD

**Issue by GDuroS** [anvilistas/anvil-extras#342]
I'm using the Routing Module of Anvil Extras in my app for a few month now and everything is working (almost) as perfect as the documentation.

Now, in one of my pages I wanted to add url_keys for queryparams my users could use to directly access and search in the page.
For exemple: accessing the my_app.anvil.app/#movies?name=Psycho will not only load the movies page directly, but it will also search for any movies with name like Psycho. 

I added a bunch of url possible keys to the route decorator, which is looking like this:
`@routing.route(url_pattern='filmes', url_keys=['nome', 'maxDuracao', 'minDuracao', 'maxRelease', 'minRelease', 'maxSessao', 'minSessao', 'reviewed', 'qtd', 'sortRelease', 'sortNome', 'sortDuracao'], title="Cadastro de Filmes | PNF Filmes", template='MainRouter')`

Then, the route stops working.
What I tried (and it worked) was having the url_keys to be just a list with only one string (the first one) and it worked.

Am I wrong to think a list of strings would work? In the docs it appears as if I could do that.

I'm using the Development version of Anvil Extras.

**Comment by stenci** [comment]
All the listed `url_keys` are mandatory. If you want some to be optional, then you need to add multiple decorators. Something like:
```python
@routing.route(url_pattern='filmes', url_keys=['nome'])
@routing.route(url_pattern='filmes', url_keys=['nome', 'maxDuracao'])
@routing.route(url_pattern='filmes', url_keys=['nome', 'minDuracao'])
@routing.route(url_pattern='filmes', url_keys=['nome', 'maxDuracao', 'minDuracao'])
```

This is obviously impractical when you have that many arguments.

When I have so many arguments, I make them all required. In my world no one creates URLs manually. I need to be able to create them on other apps or on the same app, and I need to be able to copy and paste them, but I don't need them to be short and easy to build from scratch manually.

For example this is the decorator:
```python
@routing.route('releases', title='Crating', url_keys=[])
@routing.route('releases', title='Releases - Crating', url_keys=['search', 'status', 'facility'])
```

And this is the event handler for the `click` on the `search` button and also for the `pressed_enter` of the `search_terms` textbox and the `change` of the `status_filter` and `facility_filter` dropdowns:
```python
    def search_click(self, **event_args):
        local_storage['Releases.status_filter'] = self.status_filter.text
        local_storage['Releases.facility_filter'] = self.facility_filter.text

        routing.clear_cache()
        routing.set_url_hash(url_pattern='releases', url_dict={
          'search': self.search_text.text,
          'status': self.status_filter.text,
          'facility': self.facility_filter.text,
        })
```

The idea is that, instead of processing the values in the input components when they change, I redirect to the same form with the new values in the `url_keys`. This ensures that the user can copy the URL at any time and include the current values of all the components.

The `form_show` then contains this:
```python
    def form_show(self, **event_args):
        self.search_text.text = self.url_dict.get('search', '')
        self.status_filter.text = self.url_dict.get('status') or local_storage.get('Releases.status_filter') or Status.default_filter
        self.facility_filter.text = self.url_dict.get('facility') or local_storage.get('Releases.facility_filter') or Facility.default_filter
        self.clear_search_terms.visible = self.search_text.text
```

**Comment by s-cork** [comment]
I'd be happy to include a catch all api for parameters - something like:

```python
@routing.route(url_pattern='filmes', url_keys=routing.ANY, title="Cadastro de Filmes | PNF Filmes", template='MainRouter')
```

thoughts?

**Comment by GDuroS** [comment]
@stenci 

> In my world no one creates URLs manually
Yes, of course I don't imagine anyone will manually create urls with that many arguments. My intention was to change the URL whenever the user in `my_app.anvil.app/#movies` (in the example) did the search to a url that reflected the arguments he used. That way he could bookmark or share that URL with others if that's a common search of him.

That's why the parameters would be dynamically, depending on the filled fields of the search form. I really thought that the url keys would all be optional, since they are queryParams.



> I'd be happy to include a catch all api for parameters - something like:
> 
> ```python
> @routing.route(url_pattern='filmes', url_keys=routing.ANY, title="Cadastro de Filmes | PNF Filmes", template='MainRouter')
> ```
> 
> thoughts?

I think that would solve the problem. I could just manage the ones I'm expecting and reset the URL to something using only those one in case the user but some extra, unused params.

Is that something possible to do?

**Comment by GDuroS** [comment]
> another option would be to use a redirect
> 
> ```python
> @routing.redirect("filmes")
> def redirect_params():
>     url_dict = routing.get_url_dict()
>     # now adjust url_dict to include all the defaults that may not be there
>     routing.set_url_hash(url_pattern="filmes", url_dict=url_dict, replace_current_url=True)
> ```

Redirections usually don't really work for me... Don't really know why and don't remember now what was the issue. I think it entered correctly in the method, but neither returning the new pattern or using route.set_url_hash worked. Since I was implementing I dismissed as wrong usage.

About the routing.ANY, tested here and it worked perfectly! Thank you all!


> I guess I'm late for this, but here are my thoughts anyway.
> 
> Instead of making:
> 
> ```python
> url_keys=routing.ANY
> ```
> 
> I would do:
> 
> ```python
> url_keys=[routing.ANY]
> ```
> 
> This would allow to do something like:
> 
> ```python
> @routing.route(url_pattern='path_1', url_keys=['arg_1', 'arg_2', routing.ANY])
> def path_1[...]
> 
> @routing.route(url_pattern='path_2', url_keys=[routing.ANY])
> def path_2[...]
> ```
> 
> > I think that would solve the problem. I could just manage the ones I'm expecting and reset the URL to something using only those one in case the user but some extra, unused params.
> 
> I think it would be easier to do what I'm doing: all the parameters are always listed and you assign empty values (or an empty value placeholder) to the undefined ones. Why bother picking the ones to show? Just show them all.

Implement the routing.ANY in the way you mentioned would be really cool, specially if the params captured by the routing.ANY would be specified in a different way than the others.

About showing all the parameters in the path, I think it would make the URL look ALWAYS ugly, specially in views like the one I'm implementing, with lots of filter fields. When I use put only the params for the fields used, the smart user will understand what each params means and could use directly, which is some kind of "reward" for the smart use of the application.

... Still, could do that... But if there's a better way to not use "junk" parameters, I prefer it that way.

Anyway, thanks everyone.

**Comment by s-cork** [comment]
@stenci seems sensible and easy enough to adjust see #344

**Comment by s-cork** [comment]
I've implemented in a way whereby some keys are required and the rest of the keys are catch all. 

You'd have to use `url_dict.get("foo", 42)` for the optional keys.

**Comment by GDuroS** [comment]
> I've implemented in a way whereby some keys are required and the rest of the keys are catch all.
> 
> You'd have to use `url_dict.get("foo", 42)` for the optional keys.

Ok. So, just to be sure, I will use:

- `@routing.route(url_pattern='path_1', url_keys=['arg_1', 'arg_2'])` if only those keys should be used and always used;
- `@routing.route(url_pattern='path_1', url_keys=['arg_1', 'arg_2', routing.ANY])` if arg_1 and arg_2 NEED to be present, but others are optional;
- `@routing.route(url_pattern='path_1', url_keys=routing.ANY)` if all and any param are optional.

Is that it? Or can I say which param is optional, which is required in other ways? (not asking to implement this, just to be sure if this was implemented or if it was the using one of the above syntaxes.

**Comment by GDuroS** [comment]
> > `@routing.route(url_pattern='path_1', url_keys=routing.ANY)`
> 
> `url_keys` should be a list:
> 
> `@routing.route(url_pattern='path_1', url_keys=[routing.ANY])`

Didn't test [routing.ANY], but just routing.ANY is what's working for me currently.

**Comment by s-cork** [comment]
`url_keys=routing.ANY` and `url_keys=[routing.ANY]` will be equivalent. 

> Is that it? Or can I say which param is optional, which is required in other ways? 

I haven't implemented a way to say if a specific key is optional.
The implementation wouldn't have been as straightforward as this one. 

Note @GDuroS the additional api will only work after #344 is merged.
