### ISSUE TITLE
Usage of chipInput in mobile devices

### ISSUE THREAD

**Issue by GDuroS** [anvilistas/anvil-extras#360]
Currently I'm facing a situation on one of my forms that uses ChipInputs from Anvil Extras.

ChipInputs are used by typing a value and pressing Enter to confirm that value to be transformed into a chip.

However, on mobile devices the Enter option does not exists and it works as a TAB, as showed below:
![IMG_20220705_125155](https://user-images.githubusercontent.com/92797711/177368834-1ebde2eb-ca09-4741-b6e6-a1811a14955a.jpg)

The "Outros Nomes" field is of type ChipsInput:
![image](https://user-images.githubusercontent.com/92797711/177369241-744aa495-c21b-426a-a840-5e9fd3ee1a08.png)

The keyboard I'm using is the Google Keyboard. I don't know if this happens in other keyboards as well or if there's an option in the keyboard to change this behavior (didn't find the the G-Keyboard), but I wanted to think of another solution for users that want / know how to change this and use the same keyboard on their mobile devices.

Any ideas?

**Comment by s-cork** [comment]
On IOS there's a return key on the keyboard so I haven't looked at android devices for this component.

Can you see if you're able to work with the chip components here:
https://materializecss.com/chips.html

I assume you don't have a tab button in a TextArea??

This is possible to fix but would be a slight hack I imagine.

**Comment by GDuroS** [comment]
On Android, the only one that works correctly is the autocomplete with chips (which would be extremely useful if implemented, not only for mobile, but I'm not asking this).

On TextArea I have the enter, not tab button, but you also don't need to change this. I was asking to see if anyone else has the same "issue" before or if there was another solution to the problem that I was not seeing. Didn't even report as bug.

I could identify that the user is on mobile and replace the component with another one fit for mobile. It's also a hack, but at least affects only me and not all the anvilextras user.

Unless you can see an easy way of helping me in this.

Thanks.

**Comment by s-cork** [comment]
Can you check this now on the development branch and see if it behaves as expected?

**Comment by s-cork** [comment]
just to check the obvious did you push tab? and what happened?

Since I don't own an android phone I can't really test.
Let me know if you want to have a crack at fixing it and I can suggest some tweaks for you to try.

**Comment by GDuroS** [comment]
Yeah, I did check it, it just changes the focused field and the typed text stayed there, but not as a chip. It worked like a TAB should do hahaha.

And sure, I could try to fix it, if that's an option and you have some suggestions.

**Comment by s-cork** [comment]
@GDuroS - 
1. the first thing is to get a working clone of anvil-extras
2. create the chip example
3. log some of the following:
    towards the top of the file log (around line 52) - `navigator.userAgent` and `is_adroid`
    inside the `_chip_input_key_down` log `js_event.key`
4. run the app and on your mobile and check the logs

**Comment by meatballs** [comment]
Doesn't look like anything further is going to happen on this one.
