### ISSUE TITLE
HashRouting: load_from_cache not working, when changing templates.

### ISSUE THREAD

**Issue by AugustasVol** [anvilistas/anvil-extras#367]
**Describe the bug**

- In HashRouting module.
- Using the function `set_url_hash` with `load_from_cache=False`. 
- Does not work **if the route is changing templates.**
- Loads the page from cache.

**Comment by s-cork** [comment]
@AugustasVol  - Could you provide a clone and reproduction steps

**Comment by AugustasVol** [comment]
> @AugustasVol - Could you provide a clone and reproduction steps

Sure, I'll do it in a few minutes.

**Comment by AugustasVol** [comment]
Here is an Anvil clone link that reproduces the problem.

[https://anvil.works/build#clone:WMTZNWRATRLLE2LO=CKZVU3TXKRRLJKVT2FRQYKNZ|C6ZZPAPN4YYF5NVJ=](https://anvil.works/build#clone:WMTZNWRATRLLE2LO=CKZVU3TXKRRLJKVT2FRQYKNZ|C6ZZPAPN4YYF5NVJ=)

**Comment by s-cork** [comment]
yeah - that make sense based on the implementation, I'll have to have a think about this one

**Comment by AugustasVol** [comment]
@s-cork thank you for fixing this.
