### ISSUE TITLE
Popovers being cut off by top nav bar in material design theme

### ISSUE THREAD

**Issue by jshaffstall** [anvilistas/anvil-extras#369]
The popover shown below has a title that is cut off by the top nav bar:

![image](https://user-images.githubusercontent.com/4443187/183996138-a2f4e9b7-5448-41a8-b328-3035e5b0ca08.png)

A similar situation happens when trying to put a popover onto a control on the top nav bar, any portion of the popover that overlaps the top nav bar is hidden.

It'd be nice if there were some way to set things up so popovers that overlap the top nav bar would be on top of it.  

I tried a crude zIndex approach on the popover container, which did nothing.

Here's the clone that provided the above screenshot: https://anvil.works/build#clone:YV6TXJX6VEUJGJD7=LE4R7H7QBXMYW7QHMAJPCZRU

**Comment by s-cork** [comment]
That's the default behaviour. But because you're using a custom container your popovers are now within the content rather than on the body. 

If you do some exploring of css you'll find an `overflow: hidden` somewhere in the css you can probably change to make the popover overflow it's container.

**Comment by jshaffstall** [comment]
So `overflow: visible` should work?

I tried injecting that in the main form, just before adding the popover container:

```
jQuery("""
<style>
.anvil-popover {
    overflow: visible !important;
}
</style>
""").appendTo(jQuery("head"))

popover.dismiss_on_scroll(False)
popover_container = js.window.document.createElement("div")
popover_container.style.position = "relative"
popover.set_default_container(popover_container)
```

No effect there, or just styling directly in Native Libraries.  Also tried styling `.popover`, with the same no effect.  I'm clearly not understanding something (which is par for the course for me and CSS).

**Comment by s-cork** [comment]
Not quite. You'll need to go up the component hierarchy in chrome dev tools to find which container currently has its overflow set to hidden. You'll then need to target this component's css to override it. 

It'll be there somewhere. 

I'm not at a computer to help out unfortunately.

**Comment by jshaffstall** [comment]
Ah, got it.  Will investigate and report back.

**Comment by jshaffstall** [comment]
It's the `.content` div, unfortunately.  I can't put the popover container any higher than that and have the popovers scroll with the content.  I tried setting `overflow: visible` on `.content` in Native Libraries, and the inspector says it's set, but the popover is still cut off.  The only higher element I can find with any overflow is `.nav-holder` with `overflow-y: auto`

I can get partway there by setting `.nav-holder`'s overflow to visible.  Popovers overlay the nav bar, and still scroll with the page, but now the nav bar also scrolls with the page.  That's without having a popover container at all.  

It may be that having popovers overlay the nav bar and have the nav bar remain fixed at the top of the page are mutually exclusive.

**Comment by s-cork** [comment]
@jshaffstall  I stumbled on your website and you should be able to fix the problem with the following css

```css
.appbar {
    position: fixed;
    width: 100%;
}
```

**Comment by jshaffstall** [comment]
Thanks!  That does work in the sample app I was using for testing.  Popovers are actually over the top bar, and still scroll.

**Comment by jshaffstall** [comment]
Spoke too soon.  It does work for the tutorial popovers, but the sidebar is now below the app bar.  Here's what it looks like without the styling:

![image](https://user-images.githubusercontent.com/4443187/186763614-08920dc5-3680-4213-8ce1-6ea17c14f8f1.png)

and with the styling for popovers:

![image](https://user-images.githubusercontent.com/4443187/186763695-b80118a9-f6d6-4c3d-8a64-99b9da65e058.png)

This won't affect the tutorial forms since they don't have a sidebar, so I may move the styling into just the forms that need them instead of having it globally.

**Comment by s-cork** [comment]
So I think the conclusion here is that the standard-page.html doesn't play nicely with popovers and that's not popovers fault.
Continuing to edit the html/css for standard-page.html would be the way to go to get the desired effect.

There's not really anything anvil-extras can do here so closing this issue.
