### ISSUE TITLE
Anvil_extras Routing library issue "ExternalError: TypeError: Cannot assign to read only property 'in$repr' of object '[object Object]'"

### ISSUE THREAD

**Issue by arpika99** [anvilistas/anvil-extras#370]
Hello,

**Describe the bug**
To be honest I am not sure what happened, but something broke in the routing library. Just a couple of hours ago everyhing worked.

ExternalError: TypeError: Cannot assign to read only property 'in$repr' of object '[object Object]'
at app/anvil_extras/routing/_router.py:396
called from app/anvil_extras/routing/_decorators.py:83
called from MainForm.Account, line 12 -> @routing.route('route_name', title='test_title')
called from MainForm, line 12  -> simple form import 

**To Reproduce**
I simply load the page and I get the error instantly since it occurs, when importing a form.

Unfortunately I can not share a clone.

**Screenshots**
![image](https://user-images.githubusercontent.com/55790409/185106208-e0a3a024-3c89-43db-9f85-ad2d0ad87659.png)

**Additional context**
I am using anvil_extras published version. Did an update come out or something?

**I am considering making a PR for this issue**
No

**Comment by AugustasVol** [comment]
I am also getting the same issue, not sure if it is Anvil-extras fault or Anvil's.

**Comment by rhurlbatt** [comment]
Yes we are seeing this on our production app too.
Reverting to v2.1.1 made no difference either

**Comment by s-cork** [comment]
yeah - it's nothing to do with us at this stage - it looks like a skulpt bug has crept in - anvil will be shipping a fix very soon.

I'll close this issue when that happens
