### ISSUE TITLE
Mulitselect not firing after changing enabled Status via code

### ISSUE THREAD

**Issue by bbrenter** [anvilistas/anvil-extras#371]
**the bug**
When changing the enabled Status via code the MultiSelectDropdown stops working correctly.
This affects events as well as the data binding

**To Reproduce**
I have created a sample app reproducing this issue
https://anvil.works/build#clone:5XFAXMOXQYVBXPEZ=V7YFVVFGUK3ABKWBNF2XFFRG

**temp solution**
If the version is changed to "development" the MultiSelectDropdown behaves as expected.

**Comment by s-cork** [comment]
This was already addressed and fixed. Please switch to the development version.
