### ISSUE TITLE
AttributeError: 'MultiSelectDropDown' object has no attribute '_menu_shown'

### ISSUE THREAD

**Issue by stenci** [anvilistas/anvil-extras#373]
An app uses this code to show forms:
```python
    self.content_panel.clear()
    self.content_panel.add_component(MyForm(), full_width_row=True)
```

The app can show any form without problems, but it throws the following error when trying to show any form while showing a form with a `MultiSelectDropDown`:
```python
AttributeError: 'MultiSelectDropDown' object has no attribute '_menu_shown'
at app/anvil_extras/MultiSelectDropDown/__init__.py:176
```
![image](https://user-images.githubusercontent.com/5955495/187802999-ebcdfb9f-a28d-48e0-ac61-aabe1e0398a3.png)

The offending form has an invisible `MultiSelectDropDown` that becomes visible only after other input fields have been populated. The error is thrown even after the `MultiSelectDropDown` becomes visible and has been clicked on.

Adding the last line in this snippet to the form with the `MultiSelectDropDown` avoids the error and seems to fix the problem:
```python
def __init__(self, **properties):
        self.init_components(**properties)
        self.manufacturer_dropdown._menu_shown = None
```

_(This is not my app. A friend asked for help about this error and I suggested to create the dummy `_menu_shown` member to avoid it. If you need more details, I can contact him and try to create a small cloneable app to reproduce the problem.)_

**Comment by s-cork** [comment]
Which version are they using. Can you see if switching to published or development fixes the issue. I have a feeling this isn't a bug in the latest versions.

**Comment by s-cork** [comment]
Given that the latest version has just been released and there is no reference to `_menu_shown` in that file I'm gonna assume that your friend isn't running the latest version. Or if they are it should now be fixed.

Please re-open if it's still an issue
