### ISSUE TITLE
`self.url_dict` not upated after `routing.set_url_hash(redirect=False)`

### ISSUE THREAD

**Issue by stenci** [anvilistas/anvil-extras#374]
I don't really know if this is a bug. It really felt like it because I assumed one behavior (and I wasted some time on it) while there was another one. The workaround is easy, but I would like to ask your opinion anyway.

This last line here is the one I used to fix the unexpected behavior:
```python
    def somecomponent_event(self, columns, **event_args):
        routing.set_url_hash(
            url_pattern='',
            url_dict=columns,   # columns is a dictionary identical to url_dict
            redirect=False,
        )
        self.url_dict = routing.get_url_dict()
```

My app uses `self.url_dict` and expects for it to have the current values. In my mind _current_ values includes the values set by `routing.set_url_hash(redirect=False)`.

Is my mind wrong?

Is there a good reason for `self.url_dict` and `routing.get_url_dict()` to return two different things?

**Comment by s-cork** [comment]
Yeah this seems like a bug to me. Easy fix - will get to it next week some time.
