### ISSUE TITLE
Any interest in adding my native date/time picker component?

### ISSUE THREAD

**Issue by erikcw** [anvilistas/anvil-extras#379]
**Is your feature request related to a problem? Please describe.**
I created a browser native date/time picker component as a workaround for some issues in the default anvil date picker component.  If there is interest from anvil-extras, I'd be happy to submit a PR for inclusion in the project.

https://anvil.works/forum/t/mobile-friendly-date-time-picker/4001

**I am considering making a PR for this issue**
Yes

**Comment by meatballs** [comment]
Sounds like a great idea!

**Comment by meatballs** [comment]
Doesn't look like this one is going to happen
