### ISSUE TITLE
Make Authorisation module more reusable

### ISSUE THREAD

**Issue by mjmare** [anvilistas/anvil-extras#382]
It would be nice if the function to verify if the code to check if a user has certain permissions could be called directly instead of the decorator.

**Comment by rhurlbatt** [comment]
I'm not sure but this might be better in the discussion section

Have a look at this which might do some of what you want

https://github.com/anvilistas/anvil-extras/discussions/359

**Comment by mjmare** [comment]
It seems the author has extracted some code into a separate module. But that duplicates code. By refactoring the Authorisation module one could offer two ways of using the auth code: by function calls or with a decorator.
