### ISSUE TITLE
Make Navigation module aware of Authorisation module

### ISSUE THREAD

**Issue by mjmare** [anvilistas/anvil-extras#383]
It would be nice if the Navigation object could be made aware of the permissions that a user has. Eg show/hide items depending on the perms. 

As an alternative it would be helpful if the navigiation could dynamically hide/show items. Currently only Anvil events are supported for this. A callable to determine visibility would be more flexible.

**Comment by rhurlbatt** [comment]
For the alternative check out https://github.com/anvilistas/anvil-extras/discussions/359

**Comment by mjmare** [comment]
Yeah, I do something similar now. I regenerate the menu based on the users permissions.
