### ISSUE TITLE
Any way to fix Quill translate problem?

### ISSUE THREAD

**Issue by steininge** [anvilistas/anvil-extras#386]
**Is your feature request related to a problem? Please describe.**
The Quill deletes text in edit mode when browser translation is enabled.

This is a known issue: https://github.com/quilljs/quill/issues/2286

**Describe the solution you'd like**
Is it possible to disable translation for the Quill or implement the workaround: https://github.com/quilljs/quill/issues/2286#issuecomment-882705135

**Describe alternatives you've considered**
I tried to add a div with class="notranslate" around the quill custom html component in Anvil. It didn't work. Adding "notranslate" at a higher level prevented other text elements from being translated, but the quill still did not work properly.

**Additional context**

**I am considering making a PR for this issue**
No.

**Comment by s-cork** [comment]
Could you try the following

```python
from anvil.js import get_dom_node

...

    dom_node = get_dom_node(self.quill_1)
    dom_node.classList.add("no_translate")
```

and if that doesn't work then maybe (instead of the last line above)

```python
    dom_node.firstElementChild.classList.add("no_translate")
```

**Comment by steininge** [comment]
No, that does not seem to work. 

When I inspect the html and search for "notranslate", I do not get any matches on any elements.

**Comment by s-cork** [comment]
Can you send me a clone link. When I tried it just now it worked.

**Comment by s-cork** [comment]
Can't reproduce with that link on chrome (using mac)

![QPH1V2pRFh](https://user-images.githubusercontent.com/36813890/202637999-a359cff5-3ac4-4ce4-a701-bb7090641e1b.gif)

**Comment by steininge** [comment]
The google translate extention works on Chrome for my PC too.

The problem seems to be with the built-in translation. It seems it tries to translate in real-time. 

Here from Edge:


https://user-images.githubusercontent.com/16856185/202643485-9e3bc007-cd20-448b-b730-a8d1cf4be6bb.mp4

**Comment by s-cork** [comment]
I tried with the builtin translator - also setting my default language to hindi
I don't have edge, but in chrome there was no issues
Which makes me think it's a bug in edge

You could also try any/all of the following
```python
        dom_node.classList.add("notranslate")
        dom_node.setAttribute("translate", "no")
        editor = dom_node.querySelector(".ql-editor")
        editor.classList.add("notranslate")
        editor.setAttribute("translate", "no")
```

otherwise I don't think there's a fix we can implement
https://cloud.google.com/translate/troubleshooting

**Comment by steininge** [comment]
Thanks, I'll try what you propose.

The quill does not work for two of my users in Chrome on PC. There the text is deleted while they write so the quill is always empty.

**Comment by s-cork** [comment]
Have you tried shipping the fix to your production app?
And asking those users if it's still broken for them?
Might be worth trying.

**Comment by steininge** [comment]
Yes, and it didn't work. It seems like the "notranslate" around the quill is ignored.

**Comment by steininge** [comment]
Setting the classes and attributes didn't work.

It seems like my problem is exactly what is described for the quill PR which has a solution here: https://github.com/quilljs/quill/issues/2286#issuecomment-882705135

Is this something that could relatively easily be done for the anvil quill?

**Comment by s-cork** [comment]
To implement that solution create a function in your native libraries

```python
        import anvil.js
        anvil.js.window.fixQuillTranslation(self.quill_1._quill)
```

```html
<script>

    function fixQuillTranslation(quill) {
        const updateScroll = quill.scroll.update.bind(quill.scroll);
        quill.scroll.update = (mutations, context) => {
            if (!quill.isEnabled()) {
                return;
            }
            updateScroll(mutations, context);
        }
        const scrollEnable = quill.scroll.enable.bind(quill.scroll);
        quill.scroll.enable = (enabled = true) => {
            quill.container.classList.toggle("notranslate", enabled);
            scrollEnable(enabled);
        };
        quill.container.classList.toggle("notranslate", quill.isEnabled());
    }
</script>
```

**Comment by steininge** [comment]
Thanks for your help, Stu! 

Unfortunately, fixQuillTranslation didn't solve the problem. 

I think my options now are:
- try to switch off translation for the whole app. It is a lesser solution but one that perhaps will work.
- try again to see if I somehow can make the translator leave the quill alone by node attributes/classes
- else, regrettably, replace the quill.

**Comment by s-cork** [comment]
Yeah I didn't think it would - the solution is basically the same as the simple one

Feel free to send me the link to the live app (with some demo login details if necessary) and I can take a look

**Comment by steininge** [comment]
That would be great! I'll send you a message in the anvil forum.

**Comment by s-cork** [comment]
I think the answer to this is - we can't help.
The class based solution works fine for me, but doesn't seem to work in windows.
There aren't any other solutions out there so it's not something we can fix.

**Comment by steininge** [comment]
Completely disabling the translation from my page did help with the Quill problem my client had. I will post a 'Show and tell' on how to disable translation in the Anvil forum. 

Thanks for your help!
