### ISSUE TITLE
Autocomplete accept list of tuples (<displayed>,<returned>)

### ISSUE THREAD

**Issue by lewysigns** [anvilistas/anvil-extras#397]
**Is your feature request related to a problem? Please describe.**
Currently my autocomplete displays and returns the item clicked by the user. I would like the value displayed to be different then the value returned.

**Describe the solution you'd like**
I would like a feature similar to how anvil alerts have implemented their arguement. You can input either a list of strings or list of paired tuples. 

The pair tuples would be (<Displayed text>,<Returned Value>)

**Describe alternatives you've considered**
I currently create a mapping of the displayed text and the returned value.

**Additional context**

**I am considering making a PR for this issue**
Yes

**Comment by s-cork** [comment]
Can you share the code you currently use as a workaround
At what point would expect to use return value?

**Comment by s-cork** [comment]
Closing for now due to inactivity - please re-open when you get a chance to respond to the above ⬆️
