### ISSUE TITLE
Add docs for hashrouting

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#40]
Need to do this. Adding it here as a reminder!

**Comment by hugetim** [comment]
I guess the main challenge is to translate the docs from markdown [here](https://github.com/s-cork/HashRouting/blob/master/README.md) to Restructured Text [here](https://github.com/anvilistas/anvil-extras/tree/main/docs/guides/modules).

**Comment by s-cork** [comment]
yeah that's definitely one of the factors holding this back! 
Plus I think it could do with some tweaks and it's a lot of text!

Also @meatballs had some thoughts about how we might structure our docs. 
So part of me was thinking that the routing module docs might be a good place adopt the style.
But maybe it's best just to get them in and tidy them later.
