### ISSUE TITLE
Out of date docs/bug in the persistance module

### ISSUE THREAD

**Issue by alcarney** [anvilistas/anvil-extras#407]
**Describe the bug**
The documentation for the [persistence module](https://anvil-extras.readthedocs.io/en/latest/guides/modules/persistence.html) appears to be out of date, particularly when it comes to adding new records.

- The code examples all import from `anvil_labs.persistence` and not `anvil_extras.persistence`
- The example on [adding a book](https://anvil-extras.readthedocs.io/en/latest/guides/modules/persistence.html#adding-updating-and-deleting) appears to be broken in that I only see empty rows being added to the database.

**Version**
`v2.2.1`

**To Reproduce**

1. Follow the [example](https://anvil-extras.readthedocs.io/en/latest/guides/modules/persistence.html#adding-updating-and-deleting) on adding a book.
2. See that only an empty row is added to the database.

**Note:** I was able to get something to work by changing the example client side code to the following
```python
book = Book()
book.title = "JavaScript: The Definitive Guide"
book.add()
```

**Expected behavior**
I would expect a new book to be added to the database when following the existing documentation.

**I am considering making a PR for this issue**
Yes

Happy to make a PR updating the imports in the documentation

I'm also wondering if changing the following `__init__` method on `PersistedClass` 
https://github.com/anvilistas/anvil-extras/blob/6858139e8c996cd4d0e2096ff978dccb1765c832/client_code/persistence.py#L121-L123

to 

```python
 def __init__(self, store=None, *args, **kwargs): 
     self._store = store or {} 
     self._delta = kwargs
```
would be sufficient to make the adding a book example work?

**Comment by meatballs** [comment]
Good catch and your suggestion for the init is spot on!
