### ISSUE TITLE
EditableCard docs/demo

### ISSUE THREAD

**Issue by hugetim** [anvilistas/anvil-extras#41]
I'm having trouble understanding what the EditableCard is intended to be. As far as I can tell, though, it's not working.

(What I was picturing, for the "text" datatype anyway, was a textbox with a pencil icon in the upper right (when editable=True) that allows editing it.)

**Comment by meatballs** [comment]
That probably shouldn't be in the library just yet. It's not really production ready! I'll get rid at some point...
