### ISSUE TITLE
Autocomplete Suggestion Box Cover's Text Box on Mobile

### ISSUE THREAD

**Issue by antletem** [anvilistas/anvil-extras#413]
**Describe the bug**
On a mobile device, the suggestion box of the autocomplete covers the text box. This makes it unclear as the user is still typing out their search text.

**Version**
pulished

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):
1. Set up an autocomplete
2. access your code via mobile device
3. type in autocomplete text box

**Expected behavior**
The suggestions should appear as they are in the web browser (below the text box).

**Screenshots**

Web Browser:

![image](https://user-images.githubusercontent.com/98126315/234621022-0d409c4d-7645-418b-aa64-5dd6ef9cc16b.png)

Mobile Device:

![image](https://user-images.githubusercontent.com/98126315/234621177-7dac9383-80cc-4a97-b903-5af183932467.png)

**I am considering making a PR for this issue**
No

**Comment by Csirobi** [comment]
Hi,

I can reproduce this problem in the web browser (Firefox v112.02), too.

![Autocompleted_closed](https://user-images.githubusercontent.com/12716543/236525611-a784a0eb-851f-4a4c-86be-e3c95bed5e00.png)

![Autocompleted_open](https://user-images.githubusercontent.com/12716543/236525644-7a60f759-91da-4197-a663-766b5d6d2696.png)

**Comment by s-cork** [comment]
@antletem  Can I have a clone link of a minimal example?
I don't see this on the demo app I have locally in IOS, but it could also be a conflict in some css.
Could you add information about the browser/device you're using.


@Csirobi Is this all browsers or just firefox?
Again I don't see this, so it's difficult to fix.
Clone link and steps to reproduce would be helpful.

**Comment by antletem** [comment]
Of course!

Here is a live [demo](https://hr2n3oxf3z6kalmw.anvil.app/RTZ2UZAPA4IWCP5DLGMZBS4V)

Here is  the [clone](https://anvil.works/build#clone:HR2N3OXF3Z6KALMW=5JU2AX2KVXES2MPMSHDGOBZG)

I was using my windows laptop on edge browser with the mobile mode enabled as well as safari/edge on my Iphone 13.

It is the same situation across all three scenarios.

**Comment by Csirobi** [comment]
Hi,

This the [demo](https://mvds4zmqpqina3k7.anvil.app/DJPX4452EIYILBH23MEJ4FVV)
Type the "a", and you can see the problem..


**To Reproduce**
1.  Login to your account and create a new & empty app, such as: Blank app -> Custom HTML -> Blank Panel.
2.  In the Design tab, drag&drop a Autocomplete component to the Form in the app.
3. In the Suggestions, initialize the component. (a, aa, aaa)
4. Try to run it, and type the "a" into the textbox..

Thx

**Comment by Csirobi** [comment]
Hi,

I have managed to find the problem: the core of it is the anvil banner at the top of the page for the free cloud users.
When this banner is visible, the whole app pulls down, however the position of the autocomplete popup window is not calculated correctly.
In the localhost, this problem can not be reproduced.

Thx

**Comment by s-cork** [comment]
@Csirobi thanks for the digging. There is a pr that fixes this issue. See the thread above where the PR is linked. When that's merged then you can see if the development branch fixes the issue.

**Comment by s-cork** [comment]
@Csirobi this is now merged so if you switch to the development branch of anvil-extras let us know if it's not fixed.

**Comment by Csirobi** [comment]
It works, thx.
