### ISSUE TITLE
Routing not working in provided example 

### ISSUE THREAD

**Issue by vidz1979** [anvilistas/anvil-extras#425]
Accessing an article using its hashlink takes us to Home page and not to the desired article.

https://hash-routing-example.anvil.app/#article?id=1

**Comment by vidz1979** [comment]
Commented out this part of startup and it's working now.

```
from .MainForm import MainForm

from anvil_extras import routing

routing.launch()

# from anvil.js.window import setTimeout
# for i in range(20):
#     x = lambda: routing.set_url_hash("", load_from_cache=False)
#     setTimeout(x)
```

**Comment by s-cork** [comment]
Thanks I might have left some test code in the published app. I'll take a look.

**Comment by s-cork** [comment]
Fixed
