### ISSUE TITLE
 'app/anvil_extras/Quill/__init__.py'> does not contain a class called 'Quill'

### ISSUE THREAD

**Issue by rhurlbatt** [anvilistas/anvil-extras#441]
**Describe the bug**
Not sure if this is a persistent bug or something transient that is now resolved and can be ignored. We had numerous reports come through this morning with the following
```
ExternalError: [object Event]
at app/anvil_extras/utils/_component_helpers.py, line 72
called from app/anvil_extras/utils/_component_helpers.py, line 43
called from app/anvil_extras/Quill/__init__.py, line 29
called from app/anvil_extras/routing/_router.py, line 276
called from app/anvil_extras/routing/_router.py, line 151
called from app/anvil_extras/routing/_router.py, line 151
called from app/anvil_extras/routing/__init__.py, line 182
```
Or another instance
```
ExternalError: [object Event]
at app/anvil_extras/utils/_component_helpers.py, line 72
called from app/anvil_extras/utils/_component_helpers.py, line 43
called from app/anvil_extras/Quill/__init__.py, line 29
```
![image](https://github.com/anvilistas/anvil-extras/assets/31876600/bdc70e70-71f2-420b-a24d-4c710e38955d)

**Version**
Published

**To Reproduce**
Could not reproduce at all and even users cannot reproduce after 0500 GMT today (we have not release any changes in code)

**I am considering making a PR for this issue**
No - cannot even confirm the issue at this stage

**Comment by s-cork** [comment]
This is a case where Quill is failing to be fetched externally from cdn - could be any number of reasons

you can include your own version in nativeLibraries
at which point anvil-extras won't try to fetch Quill when the module is loaded

`<script src="//cdn.quilljs.com/1.3.6/quill.min.js"></script>`
