### ISSUE TITLE
Optional e-mail - not working

### ISSUE THREAD

**Issue by vidz1979** [anvilistas/anvil-extras#446]
When I try to use this schema with an empty string, it throws an Error:

```email_schema = z.string().email().optional()```

Zod is not obeying `optional`. Tested with `not_required()` too. Is there a workaround for this?

**Comment by s-cork** [comment]
I think you want it to be empty rather than optional. Optional is None or the thing. Not required means it doesn't exist in a typed dict. 

It's a bit convoluted but this should work:

```python
z.string().email().optional().or(z.literal(''))
```

If you search the web for this issue you'll get similar suggestions (and similar frustrations)

**Comment by vidz1979** [comment]
Thank you, Stu!
