### ISSUE TITLE
Pivot not working with new Material Design 3

### ISSUE THREAD

**Issue by akrishnamo** [anvilistas/anvil-extras#447]
When I include the pivot component, i get an error message "An error occurred rendering the PivotTable UI." with the following error message in console......

_WARNING: This application uses deprecated jQuery 2.2 features. Please see the Javascript console for more details. Error: jQuery.expr[':'] is deprecated; use jQuery.expr.pseudosWARNING: This application uses deprecated jQuery 2.2 features. Please see the Javascript console for more details. Error: jQuery.fn.mouseup() event shorthand is deprecatedWARNING: This application uses deprecated jQuery 2.2 features. Please see the Javascript console for more details. Error: jQuery.fn.delegate() is deprecatedWARNING: This application uses deprecated jQuery 2.2 features. Please see the Javascript console for more details. Error: jQuery.isArray is deprecated; use Array.isArray_

**Comment by s-cork** [comment]
Does it render?
The error message is expected behaviour.

**Comment by akrishnamo** [comment]
My bad, got confused from the screen UI message and did not pursue it.

Works without issue, closing.
