### ISSUE TITLE
Typo in assertion message: all tranistion must be lists

### ISSUE THREAD

**Issue by stenci** [anvilistas/anvil-extras#449]
https://github.com/anvilistas/anvil-extras/blob/5b55493cae51168f30b35e81a2be45577e1c1c2f/client_code/animation.py#L82

It is: all tranistion must be lists
It should be: all transitions must be lists

**Comment by s-cork** [comment]
Might be worth looking at PR-ing this typo fix. I'm not at a computer for the next week or so. And I think @meatballs is also busy at the moment.

**Comment by stenci** [comment]
> Might be worth looking at PR-ing this

Yeah... but that would require me cloning the repository and knowing how to make a PR. I have tried in the past, and the success rate has always been very low. Github and I don't like each other.

Since this is a little typo that doesn't bother anyone, I thought it would be easier for you to slip it in the next time you put your hands on it.
