### ISSUE TITLE
Navigation module ignoring @navigation.register decorator when using Hash Routing

### ISSUE THREAD

**Issue by RicardoFernandez-UY** [anvilistas/anvil-extras#452]
### Discussed in https://github.com/anvilistas/anvil-extras/discussions/451

<div type='discussions-op-text'>

<sup>Originally posted by **RicardoFernandez-UY** September 12, 2023</sup>
Hi,

I’m trying to use the anvil-extras Navigation together with the Hash Routing navigation method.
I use the Navigation module for generating the menus dinamically, and I want to display the Form titles using its functionallity, in order to display a different title for each form in the Title slot of the template form (the one that holds the menu).

Here is what I’ve done:

I started with the Hash Routing only. Everything worked ok.
Then, I introduced the Navigation module, and made the required changes.

At this point the Navigation module is taking the task by generating the menus and the events needed to navigate to the target forms (set_url_hash(sender.tag.target)), as stucork explained to my in another post. 
But the Navigation module still needs the @routing.route from the Hash Navigation, to be present. Otherwise it does not work.

Here comes my confusion about how this is working at all, because per documentation:

```
In order for a form to act as a target of a menu link, it has to register a name with the navigation module using a decorator on its class definition.
For example:
@navigation.register(name=“about”, title=“About”)
```

And I’m not using @navigation.register anywhere.
I did try using it, because I wanted to display the Title of the Form, but it completely ignores it.

So, I’m clearly missing something here. What could that be?
In summary, how is this navigating to the target forms if I haven’t registered them with the Navigation module?, and why when I use the @navigation.register, it ignores it and so the title functionallity?

```
Here is the link to a minimum version of the app.
https://anvil.works/build#clone:E7LKCQ22EHWX64DL=LL6ZM2STKEW2HBOYJ22K5C6E
```
You will see the menu items defined in the visual designer, which are the ones I used for working directly with the Hash Routing + nav_click event, at the beginning, and also the dinamically generated links  (the ones with icos) using the Navigation menu, which are the ones that are working now.

Thank you !!!</div>

**Comment by s-cork** [comment]
Hi can you re-write this issue. The text isn't really relevant to the issue title anymore. Linking to the discussion is enough and doesn't need a copy of the text. 

I think the issue is really that there is no way to set the title when using the navigation module with hash routing.

**Comment by RicardoFernandez-UY** [comment]
> Hi can you re-write this issue. The text isn't really relevant to the issue title anymore. Linking to the discussion is enough and doesn't need a copy of the text.
> 
> I think the issue is really that there is no way to set the title when using the navigation module with hash routing.

Sorry, first issue ever. I'll rewrite it.

**Comment by s-cork** [comment]
When writing issues there should be a couple of templates to select from which will help.

**Comment by RicardoFernandez-UY** [comment]
Now I used one of the templates, but they just show a box for the title and a box for the description. 
If you find that it is still not well defined, please feel free to correct it, and tell me, so I can check it out to learn how it should be done.
Thank you!
