### ISSUE TITLE
No way to set the title when using the navigation module with hash routing.

### ISSUE THREAD

**Issue by RicardoFernandez-UY** [anvilistas/anvil-extras#453]
When using the Navigation module together with Hash routing, the @navigation.register is ignored and so there is no way to set the title of the form using the module.
More details in #451.

**Comment by s-cork** [comment]
@meatballs my initial though is to move/copy this to the build_menu argument and then the nav_link click event handler can also call set_title if it has a tag.title

**Comment by RicardoFernandez-UY** [comment]
For now I've done this:
```
  def on_navigation(self,**nav_args):
    hash = routing.get_url_hash()
    # Use the menu Text as the Title
    # Use a list comprehension to find the corresponding Title value
    title = next((item["text"] for item in menu if item["routing"] == "hash" and item["target"] == hash), None)
    self.form_title.text = title
```

And it works fine. Being form_title a label I punt in the Title slot.
So, as @meatballs said, if you could add this as an additional key in the menu definition dictionary,  and later on use it in the build_menu function, I think that would be it.
