### ISSUE TITLE
Augment trigger('writeback')

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#46]
just an idea based on this post
https://anvil.works/forum/t/why-no-refresh-data-bindings-for-write-back-data-binding/8211/

I can see an argument for adding a writeback feature only for textbox/textarea components to trigger writeback on change. The current way to do it is verbose and requires too much boiler plate.

I could potentially add the method to trigger method that already exists in the augment library.

```python
from anvil_extras import augment

def textbox_change(self, sender, **event_args):
    sender.trigger('writeback') # all writeback properties get written back on this component
```

The writeback would be on the component rather than on the Form so it would be different to the feature request. 
https://anvil.works/forum/t/please-support-refresh-data-bindings-for-write-back-as-well/8226

Thoughts?

Alternative apis

```
augment.writeback(sender)
augment.trigger_writeback(sender)
```

**Comment by meatballs** [comment]
I like that. It feels better for it to be on the component rather than the form.

Couple that with validation on the underlying object (hence the ORM issue), and we have something very nice indeed!
