### ISSUE TITLE
Internal error using popovers

### ISSUE THREAD

**Issue by stenci** [anvilistas/anvil-extras#474]
I think this is an Anvil problem rather than an Anvil Extras problem, because it reproduces also with an older version of Anvil Extras that used to work. But I see this problem when working with Anvil Extras, so I will start by reporting it here. Let me know if I should report it on the Anvil forum or support.

---

I tried to use the Validator example app, I noticed some popovers failing to show and I had many internal errors. I used it last time long time ago, and everything was working well.

The message in the console is:
```
[An internal error has occurred] - see browser console for more details
ResizeObserver loop completed with undelivered notifications.
```
See the snapshots below for more details about app and browser consoles.

The code in the Validator module includes a loop to assign `pop` and `popover` to `TextBox`, `TextArea`, `DatePicker `and `DropDown`. I think this is not required any longer because of [this](https://github.com/anvilistas/anvil-extras/commit/42220824584c9822a39d3e46b6b73e3c7f1a8e72#diff-f7833e107d6c423d86330fc79e2a41481aec9a5ed2cea23e1f5c5fbae681d773R167-R170). I tried removing that assignment, but it seems to have no effect.

I tried to set the dependency version to 1.5, which was before the commit mentioned above. With the 1.5 the popovers don't scroll with the page because that version didn't manage their scrolling, but the internal errors still pop up.

So this internal error problem doesn't seem to be caused by changes in Anvil Extras, it's more likely to have changed because of changes in Anvil.

Here is the [clone link ](https://anvil.works/build#clone:TCCWPPUBDJMPIWX4=Y6QDCDNROKQMLDUGHBOM7SN3|UEEIN3XGMBCNRUHT=QFOWTB4ARFLIQOFPIDIZJGHE) for both the Validator and the Validator example apps.

The problem doesn't reproduce reliably, but it's very likely to reproduce by:
- Start the app
- Click on "With Popovers"
- Make sure the vertical scrollbar is visible by shrinking the running app window vertically
- Press "1" and "tab" a few times in order to create invalid inputs and show a few popovers
- Scroll down and click on "Validate all"
- Repeat a few times. Sooner or later the errors will show up. Clicking on "With Labels" and then on "With Popovers" may increase the chances of reproducing the error. Or may not.

![image](https://github.com/anvilistas/anvil-extras/assets/5955495/482a2698-ab44-4434-8846-6d6887b5f0ff)

![image](https://github.com/anvilistas/anvil-extras/assets/5955495/a18ce848-47f5-4cef-8290-665201de971e)

**Comment by s-cork** [comment]
We can't really fix this
And I don't think it's an Anvil thing
The error is coming from bootstrap/jquery and seems to be a race condition between creating and destroying popovers

Reproducing it is easy enough if you remove all validation except for the textbox with two rules
Then hit 1 and tab on that that text box

The two rules thing here is part of the issue
lots of event handlers, lots of creating and destroying popovers on the same component

when you change and hit tab then you can get what feels like an odd exectuion order,
`change rule1, change rule 2, lost focus rule 1, lost focus rule 2`
One event handler might give back control to the event loop while another one starts
e.g. one event handler gives back control to the event loop waiting for a popover to be destroyed, while another one gets control of the event loop and is creating a popover on the same component with different text

That's the asynchronous nature of the browser i'm afraid

But here's some code that mitigates agains the issue
After implementing it I didn't see any errors

```
    def _set_label(self, is_valid, component, error_label, message, default_message, placement):
        if error_label:
            error_label.visible = not is_valid
            if not is_valid:
                error_label.text = message or default_message
        else:
            txt = message or default_message
            if is_valid:
                if component in self._components_with_popover and self._components_with_popover[component] == txt:
                    del self._components_with_popover[component]
                    component.pop('destroy')
            if not is_valid:
                if component not in self._components_with_popover:
                    component.popover(txt, trigger='manual', placement=placement, auto_dismiss=False)
                    component.pop('show')
                elif self._components_with_popover[component] != txt:
                    component.pop('destroy')
                    component.popover(txt, trigger='manual', placement=placement, auto_dismiss=False)
                    component.pop('show')
                elif not pop(component, "shown"):
                    component.pop("show")
                self._components_with_popover[component] = txt
```

**Comment by stenci** [comment]
Any idea why I had never seen this error in the past and I see it now?
Maybe something has changed on the bootstrap side?

---

Thanks for trying to mitigate the problem. 

Your changes should have been there from the beginning, the behavior is just cleaner. But they seem to help with decreasing the number of "TypeError: Cannot read properties of null (reading 'off')" errors, but don't decrease the number of internal errors.

For example, if you type 1 on every field, click on validate all, then click on "With Labels", then "With Popovers", you have 100% chances of getting internal error at the first, third and then every time you change the form. This reproduces even with a window tall enough without scrollbar.

---

I didn't know about the `'shown'` behavior, I guess I missed it. Is there a particular reason why you have used the `pop(component, "shown")` form rather than the `component.pop("shown")` one?

**Comment by s-cork** [comment]
That doesn't reproduce it for me
It could also be a browser thing

It would be useful to know since when you noticed the errors
And whether it seems browser specific or not

---

I added the final "shown" check because if the page gets scrolled all the popovers are hidden and don't seem to come back

**Comment by s-cork** [comment]
Another idea you could try is to hold to a reference to an `error_label` instead of the text of the error
This way you might never need to call `destroy` and could just call `hide` instead
And any time the text changed you could just do something like:

```python
    def _set_label(self, is_valid, component, error_label, message, default_message, placement, **e):
        if error_label:
            error_label.visible = not is_valid
            if not is_valid:
                error_label.text = message or default_message
        else:
            txt = message or default_message
            error_label = self._components_with_popover.get(component)
            if is_valid:
                if error_label is not None and error_label.text == txt:
                    component.pop("hide")
            if not is_valid:
                if error_label is None:
                    error_label = Label(text=txt, spacing_above="none", spacing_below="none")
                    self._components_with_popover[component] = error_label
                    component.popover(error_label, trigger='manual', placement=placement, auto_dismiss=False)
                elif error_label.text != txt:
                    component.pop("hide") # prevents popover jumping
                    error_label.text = txt

                if not pop(component, "shown"):
                    component.pop("show")
```

```
