### ISSUE TITLE
Think there is a bug with v2.5.2

### ISSUE THREAD

**Issue by mcmasty** [anvilistas/anvil-extras#476]
**Describe the bug**

TypeError: Link got unexpected keyword argument(s): 'condition'
at app/anvil_extras/navigation.py:157

**Version**
I am using the 'Published' version.  If I downgrade back to 2.5.1 the issue does not happen.

**To Reproduce**
Clone this app
Make sure dependency is `Published` or `v2.5.2`

https://anvil.works/build#clone:2V3PIBL6WCYKKRO6=W4AM7EKAJXNT4B46XAIDSCME|null

**Expected behavior**
The app to start.

**Screenshots**
<img width="574" alt="Screenshot 2023-10-25 at 11 20 22" src="https://github.com/anvilistas/anvil-extras/assets/6108038/68b9376d-b6f9-4a18-a071-6630009c30f1">

**I am considering making a PR for this issue**
No.

**Comment by s-cork** [comment]
should now be fixed - the published branch got out of sync
