### ISSUE TITLE
Validator

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#48]
We should triage the validator for the orm and include similar syntax as a complementary set of functions/decorators here.

I've always found the anvil Library validator component a little tricky to use and a simpler api would be great.

This combined with `auto_refreshing` would work really well I think.

`auto_refreshing` triggers the refresh_data_bindings which in turn will trigger the event handler so the idea here would be that you can do your validation inside the event handler `refreshing_databindings`.

**Comment by mjmare** [comment]
If you create a validator system, please enable use without the ORM. I'd really like to see a solid validation framework in Anvil.

**Comment by s-cork** [comment]
Superseded by #122
