### ISSUE TITLE
Tab Control - set the "active" background colour for a tab in code rather than just by clicking it.

### ISSUE THREAD

**Issue by telemix** [anvilistas/anvil-extras#481]
When the tab control first renders, none of the tabs have the "selected" background colour, and setting the "active_tab_index" in code does not change the background colour in the way that clicking it with the mouse does,

I would like that setting "active_tab_index" would also set the background colour for the tab in the same way that clicking the tab does.

**I am considering making a PR for this issue**
No - I wouldn't know where to start :)

**Comment by s-cork** [comment]
Note clicking away doesn't keep the background colour. If you click somewhere else on the page the tab is no longer active and so the background reverts. 

So really you want a way to set the background color of the active background fullstop

**Comment by telemix** [comment]
> Note clicking away doesn't keep the background colour. If you click somewhere else on the page the tab is no longer the active element and so the background reverts.

I had not noticed that - indeed it does.

> So really you want a way to set the background color of the active background fullstop

Yes, you are correct. Should I update the FR or are the notes enough?

**Comment by s-cork** [comment]
It's not on the production branch yet - it's pencilled in for the next release
to test it you'll have to try the development branch
Would be good to try that and see if it works as you expect it to

**Comment by telemix** [comment]
It's working on dev branch now. That's much better. The only thing I would say is that I still can't get the initial tab to show as selected. You have to click on them. But when you do, they stay marked as selected when focus is lost, which is great.

**Comment by s-cork** [comment]
did you go to the properties panel and set the color for `active_background`

**Comment by telemix** [comment]
Ah, not on the control I was testing, no. Apologies. That seems to work perfectly! Thank you both,
