### ISSUE TITLE
Issue with latest Anvil Extra changes

### ISSUE THREAD

**Issue by JonWakefield** [anvilistas/anvil-extras#490]
Hello, I am encountering a bug I believe to be related to the pull request #488 that occurred a few days prior. 

When I use a previously saved version of anvil-extras in my project, everything works as it should. However, when I clone the latest version I get an error & I am unable to load any content inside of the content panels.

Here is the traceback:
![Screenshot from 2023-11-28 11-40-52](https://github.com/anvilistas/anvil-extras/assets/67289517/446b9ab1-be2b-49d1-9d0a-1a521d490872)

I noticed #488 is related to the augments.py module, the module seemingly causing the error I am currently having.

**Describe the bug**
The content panel is unable to load any content.

**Version**
Using the latest version from the Github repository, I encounter this bug. 
(I need my customers to be able to run a shell script that runs the command 'git clone https://github.com/anvilistas/anvil-extras')

**Screenshots**
Here is a screenshot of what my anvil project looks like when I encounter the bug (notice the empty content panel.)
![image](https://github.com/anvilistas/anvil-extras/assets/67289517/113f1d09-b61f-4083-8469-608882081016)

I can click on the left-hand side nav bar but each form looks the same, nothing is able to load.

**Additional context**
If there is a way for me to run 'git clone' but use a previous build of anvil extras (before pull request #488) that would also be a solution I can try out.

Thanks for the help. Please let me know if there is any other information I can provide to help

**Comment by s-cork** [comment]
It's not clear what the bug is. Are you getting any error messages?

Are you using augment in your project?

**Comment by JonWakefield** [comment]
Thanks, #492 fixed the error I was having.

Appreciate it!
