### ISSUE TITLE
Augment has a bad refrence

### ISSUE THREAD

**Issue by lewysigns** [anvilistas/anvil-extras#491]
**Describe the bug**
This doesn't prevent the module from working or raise an error when running.

It is an error message in the Designer Output in the Anvil IDE

**Version**
2.5.4

**To Reproduce**
add this line of code to a form

```python
augment.set_event_handler(self,'click',self.button_clicked)
```

**Screenshots**
<img width="651" alt="image" src="https://github.com/anvilistas/anvil-extras/assets/66562010/3bfe8703-1af0-4368-98c3-1cf81b9dab10">

**Comment by s-cork** [comment]
Can you try the development dependency. I think this is already fixed.

**Comment by lewysigns** [comment]
Already fixed! Thanks @s-cork !
