### ISSUE TITLE
Use of external hosts cdn.skypack.dev (nouslider) and cdn.jsdelivr.net (bootstrap multiselect?!)

### ISSUE THREAD

**Issue by ArneBenedikt** [anvilistas/anvil-extras#493]
I am using from Anvil Extras the Multiselect and the Slider and am loving it.

Using the library seems to make calls to two external hosts (see picture) though.

<img width="391" alt="Bildschirmfoto 2024-01-03 um 14 31 57" src="https://github.com/anvilistas/anvil-extras/assets/116294425/d2c037d4-580b-42be-a0cf-0ce4eb2ceba8">

I have some reservations in using external hosts and would prefer everything in one dependency. My preference would be that all necessary dependencies are within Anvil Extras / Anvil.

**Comment by s-cork** [comment]
Using external cdn providers is not something we will be changing. 
In some components we support adding your own implementation by putting the required js/css files in your theme assets and adding appropriate script/link tags in your native libraries. But I don't think that's supported for these two components. 

If you'd like to explore this option let me know and we can create a path for you to do that. 

There are some advantages of using external cdn providers. Performance being one of them.
