### ISSUE TITLE
Error: SyntaxError: Syntax error in data binding for self.label_5.text in form Demo

### ISSUE THREAD

**Issue by informatica2jbm** [anvilistas/anvil-extras#509]
**Description**
I have installed the dependencies for 'anvil.extras,' and when I run the program, it returns the error that I have put in the title: 'SyntaxError: Syntax error in data binding for self.label_5.text in form Demo.' I don't have any form named 'Demo' or any label named 'label_5.'

And in fact, when I remove the dependency, the error disappears, and I can test the app without any problem.

What could it be due to?"

**Version**
Version "Published" (it seems the last version is 2.6.0

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):
1. Go to Settings
2. Click on Dependencies
3. Click on "Third-party" button
4. Add the third-party dependency code (C6ZZPAPN4YYF5NVJ)
5. Click on Run
6. See error

**Expected behavior**
I simply expected the program to work

**Screenshots**
With anvil-extras dependencies installed
![image](https://github.com/anvilistas/anvil-extras/assets/160256499/01a3e28b-f751-4a8e-bb0a-5c0de114afcd)

Without anvil-extras dependencies installed
![image](https://github.com/anvilistas/anvil-extras/assets/160256499/12026895-5f44-406a-bd44-7647abb6347f)

**Comment by s-cork** [comment]
Are you using python 2 on the client?
If so we don't support python 2 on the client
go to settings / python versions / advanced settings and change the client code version to python 3

If you know how you ended up with python 2 let us know and we can follow it up

**Comment by informatica2jbm** [comment]
I'm using Python 3.10 (Beta)

**Comment by s-cork** [comment]
That's the server code. Check the client version. 

Either follow the steps above. Or do 
```python
import sys
print(sys.version)
```

In a client module.

**Comment by informatica2jbm** [comment]
Yes! It was that, thank you!
