### ISSUE TITLE
authorization: option to use UserMap table instead of Users table

### ISSUE THREAD

**Issue by yahiakala** [anvilistas/anvil-extras#515]
**Is your feature request related to a problem? Please describe.**
I want to use the authorization module without adding a column to the Users table (it is shared between apps).

**Describe the solution you'd like**
I want to create a UserMap table that has a column called 'user' which is a single row link to the Users table. Another column will be 'roles' which will be a multi-row link to the Roles table.

**Describe alternatives you've considered**
- Not sharing the Users table between apps
- Sharing Users, Roles, Permissions table between apps
- Using simpler authorisation setups from the forum

**Additional context**
<img width="984" alt="image" src="https://github.com/anvilistas/anvil-extras/assets/24422258/2697e7c4-d900-478c-9fc0-02a1466212de">

**I am considering making a PR for this issue**
Yes. If there's no interest, I'll just throw it in my anvil-squared dependency instead.

**Comment by s-cork** [comment]
Yeah sounds like a nice feature. 

I imagine setting up some sort of config option for the authorisation module will suffice, ensuring the default option is the current behaviour.

**Comment by rhurlbatt** [comment]
I think this would be handy if it ends up being built.

**Comment by yahiakala** [comment]
Moving this discussion to the PR #516
