### ISSUE TITLE
pagination Event handlers for datagrid

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#53]
Not sure it's something for this library

Forum link
https://anvil.works/forum/t/events-on-pagination-buttons/8556/4

Could maybe go in augment

```python
from anvil_extras import augment

self.data_grid.set_event_handler('pagination_click', self.pagination_click)
```

I have the code written for this

What do you think?

**Comment by meatballs** [comment]
Why not? Somebody obviously has a requirement for it!
