### ISSUE TITLE
MulitSelect leaves menu open if navigating with mouse

### ISSUE THREAD

**Issue by Rick-VIPER** [anvilistas/anvil-extras#536]
**Describe the bug**
If you open a Multiselect items menu and then navigate without clicking outside the menu, the menu does not close when the form is uloaded

**Version**
Published

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):
1. Open a multiselect menu
2. Navigate / unload the form without clicking

**Expected behavior**
On Navigation or form unload the menu should close

**I am considering making a PR for this issue**
No - I would have no idea where to even start sorry

**Comment by s-cork** [comment]
Note to self: Probably just needs a call to close on the hide event of the multi select component.
