### ISSUE TITLE
Multiselectdropdown 'select all' option is cut off

### ISSUE THREAD

**Issue by yahiakala** [anvilistas/anvil-extras#545]
**Describe the bug**
The 'select all' and 'deselect all' options are next to each other and getting cut off in the dropdown. I have tried to have the width set to 'auto' and 'fit' and having the same problem.

**Version**
Published app - using the App ID as a dependency.

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):
1. Add a multi-select drop down to a form
2. Populate it with a bunch of options
3. Select 'enable_select_all'

**Expected behavior**
The width of the dropdown should be wider than the text.

**Screenshots**
![image](https://github.com/user-attachments/assets/7a659059-9858-489a-b441-2d0c774a60c6)

**I am considering making a PR for this issue**
No. I have disabled 'enable_select_all' to deal with this issue.

**Comment by s-cork** [comment]
Could you provide a minimal example clone link
Following those instructions doesn't show the issue for me
I suspect it's something to do with some css

**Comment by yahiakala** [comment]
Here's a minimal example: https://anvil.works/build#clone:XSS33QAN6IQ5IF6L=EAD7VSTHC2JT4DLGG6HRREUZ

Basically, 'auto' and 'fit' are not taking into account the width that is required for the 'select all' and 'deselect all' buttons. If the options are less wide, the dropdown will be less wide.
