### ISSUE TITLE
Async server calls out of order?

### ISSUE THREAD

**Issue by jshaffstall** [anvilistas/anvil-extras#547]
**Describe the bug**
I think I'm seeing async server calls executed out of order, when synchronous calls are mixed in.  

**Version**
2.6.2

**To Reproduce**

Using the following clone: https://anvil.works/build#clone:4QQQ3FNAUHGIMTMO=T3YSEKX3YPG2UW55YQXUP7QB

1. Click the button quickly
2. Check console output for out of order numbering

**Expected behavior**
I was hoping for the numbering to be consecutive, showing that mixed async and synchronous server calls were queued up and executed in order.  

With the timer disabled in the app, all the async calls execute in the right order.  It's only when the synchronous call is happening in the middle of them that async calls get out of order.

**Screenshots**
Here's one example of several async calls running between two synchronous calls, where the async calls end up executing out of order:

Server called, count: 17, async: False
Server called, count: 18, async: True
Server called, count: 19, async: True
Server called, count: 21, async: True
Server called, count: 22, async: True
Server called, count: 20, async: True
Server called, count: 23, async: False

**Comment by s-cork** [comment]
Ok - i've looked at the internal code, and there's no guarantee that the order you create the requests is the order they will execute.

A server call won't start until another one has finished (so they won't run in parallel)
But, which server call get's picked up next is not guaranteed to be the next one in creation order.

This might be exaggerated with media objects in calls.
But even without media objects it's not guaranteed (as your output shows - though it's also possible that anvil is reporting the output out of sync)

I don't think we reference guaranteed order in the docs.
But feel free to add a caveat to the docs, that execution order is not guaranteed, and code should not expect it to be such.

**Comment by jshaffstall** [comment]
We'd had a similar issue with Python calls being made out of order (this is in David's project), and solved that one by giving each call an id and putting it into a list.  When the call was woken up, it executed if its id was at the start of the list, otherwise it yielded control to the event loop to give another call a chance.  

Does that sound like something that might work in this context to guarantee execution order?

**Comment by s-cork** [comment]
Maybe. But it also feels like it's not something that needs to happen at the library level. If you're using async and you need execution order to work then the call primitive is not the right place for it. Note the call primitive also takes a function that you can call asynchronously, not just the name of a server function. 

We could create a different primitive. 
It's also possible that anvil.server.call might one day support parallel calls, at which point you'd probably want that to be done with the async machinery. 

Feel free to post a clone link or code snippet and we can think about where it might fit.

**Comment by s-cork** [comment]
closing for now
