### ISSUE TITLE
Popovers break when Layouts are enabled because the open form lacks "add_component()" method

### ISSUE THREAD

**Issue by LuisSala** [anvilistas/anvil-extras#553]
**Describe the bug**
Popovers broken when Layouts are enabled. This is due to the fact that the open form lacks an `add_component()` method. Fortunately, the open form does have a "layout" property that does possess the `add_component()` method. A hacky "fix" is provided at the bottom of this issue.

**Version**
Which version of anvil-extras are you using?
Version 2.6.2

**To Reproduce**
Steps to reproduce the behaviour (including a clone link when applicable):
1. Create a form called "MyLayout", such as a material design layout 
2. Convert the form to a Layout per the instructions [in the Anvil docs](https://anvil.works/docs/ui/layouts)
3. Add a slot to the layout.
4. Add a button or other element to a menu location (such as the top menu bar) and attach a popover to it in the `__init__` method. Also add a click handler to the button. Example code follows:
```python
### In __init__():
self.my_button.popover(content=MyMenu(),
                               placement="bottom",
                               trigger="manual",
                              )
### Button Click Handler
def my_button(self, sender, **event_args):
    """This method is called when the button is clicked"""
    self.my_button.pop('toggle')
```
5. Create a second form to represent the popover menu (e.g. `MyMenu`) referenced in step 3.
6. Create a form "MyForm" that uses the above layout.

When running the app and clicking on the button, you will see an error occurs of the type:
`AttributeError: 'MyForm' object has no attribute 'add_component'`

**Expected behavior**
We would expect a popover to appear

**Hacky Fix**
I temporarily fixed it by modifying the `fire_show_event()` function of `client_code/popover.py` to check if the `open_form` contains a layout. If so, I call `add_component` within the layout. There's probably a more elegant (or more Pythonic) solution, but this seems to work for now.
```python
    def fire_show_event(e):
        if component is None:
            return
        open_form = _anvil.get_open_form()
        if open_form is not None and fake_container.parent is None:
            if "layout" in dir(open_form):
              open_form.layout.add_component(fake_container)
            else:
              open_form.add_component(fake_container)
        if component.parent is None:
            # we add the component to a Container component
            # this doesn't really add it to the dom
            # it just allows us to use anvil's underlying show hide architecture
            fake_container.add_component(component)
```
**I am considering making a PR for this issue**
No

**Comment by s-cork** [comment]
thanks for reporting - yeah there are few incompatibilities between anvil_extras and layouts here and there

I think we might need some extra api from anvil to make this work
but a variation of your fix might work for now
