### ISSUE TITLE
Can't use css variables as foreground value for Tabs

### ISSUE THREAD

**Issue by GDuroS** [anvilistas/anvil-extras#568]
**Describe the bug**
The foreground field of Tabs is not allowing texts using css variables. The field highlights and erases everything that is typed after loses focus. This does not occour in the background field of the same component.

**Version**
3.0.0

**Screenshots**
![image](https://github.com/user-attachments/assets/691df639-d8e9-4ee4-abab-913a6e9f30ea)

**Comment by s-cork** [comment]
Ok - i've added a PR to add this support
note for css vars for foreground we would expect 3 space separated numbers foreground
e.g. `255 0 0`
This is because we wrap the color in `rgb(color)` and `rgb(color / opacity)`

**Comment by s-cork** [comment]
@GDuroS  - if you try master branch and see if it's working better for - keep in mind the restrictions above for what is a valid css var for tab foreground.

**Comment by GDuroS** [comment]
@s-cork - Just checked and allowed me to type a css var. It didn't work (as expected), however, since my vars are usually hex codes. Changing it to a 3 numbers value worked, but I don't really know if it will be useful for me, since I would need to change a lot in my "custom theme" service for users.
Anyway, thanks for the work!

**Comment by s-cork** [comment]
ok - another PR should help - there's new browser syntax that will make this possible

**Comment by GDuroS** [comment]
Oh, I Wasn't really complaining, I was ok to continue changing the foreground using roles + css, but thank you!

**Comment by s-cork** [comment]
Can you have another go @GDuroS  and see if now works like you want?
Note this may not work in older browsers

**Comment by GDuroS** [comment]
Sorry for the delay, @s-cork. I can confirm that it worked on the master branch! Thank you!
