### ISSUE TITLE
Use a custom format logger to print Publisher messages

### ISSUE THREAD

**Issue by GDuroS** [anvilistas/anvil-extras#569]
**Is your feature request related to a problem? Please describe.**
When using the Publisher class to publish or subscribe to a channel you can pass a parameter called "with_logging" to override the default way for printing in the console output.

Printing, however, would break the flow of logs when using a custom format of Logger (also from anvil-extras).

It would be interesting if the Publisher construtor and it's methods could receive a Logger instance to use to print in the correct format.

![image](https://github.com/user-attachments/assets/eccf014c-49fa-43c3-abd4-f70a96d7fb7e)

![image](https://github.com/user-attachments/assets/4b291bb9-4987-4740-8962-1bea33e9691c)

![image](https://github.com/user-attachments/assets/c49d4e03-3dab-47a7-8a74-de592360e837)

The Level could be INFO (by default or as parameter) and the same message printed now could be the msg parameter of the logger format.

**Comment by s-cork** [comment]
@GDuroS did you want to work on this PR

**Comment by GDuroS** [comment]
@s-cork Sure, I could do this.

**Comment by GDuroS** [comment]
@s-cork I made the pull request, but to be honest, this is the first time I did a PR. If I did something wrong, let me know.
