### ISSUE TITLE
We don't support IE

### ISSUE THREAD

**Issue by s-cork** [anvilistas/anvil-extras#76]
anvil still does.
anvil-extras definitely doesn't

we should make a note somewhere in our docs.

**Comment by meatballs** [comment]
Fine - but if anvil does, that's lost on me. One of my clients has users who routinely use IE and start to report problems with the apps we've written which magically disappear when the switch to absolutely anything else.

**Comment by s-cork** [comment]
closing - I don't think we need to add this to the docs.
By the time we get round to it IE will have less and less support anyway.
