### ISSUE TITLE
Clone link for a demo?

### ISSUE THREAD

**Issue by hugetim** [anvilistas/anvil-extras#78]
I'm excited about the new installation instructions, but only installing it as a third-party dependency means I can't see and play with the demo code demonstrating the components. Maybe create a separate "Extras Demo" app that has Extras installed as a third-party dependency, and provide a clone link to the demo app?

**Comment by meatballs** [comment]
Personally, I don't like the way clone links expose my email address so, until my [feature request](https://anvil.works/forum/t/option-to-hide-my-email-address-in-clone-links/7960) to fix that is implemented, I'd rather not include one.

If you want to play around with the demo code, you can always git clone this repo locally and then force push it to a new anvil app on your account.

**Comment by hugetim** [comment]
Is it cool if I create an unofficial Extras demo app (partly for my own learning) and share a clone link to that on the forums? I'd start from the built-in demos for components here and then add demos of anything missing, such as the Navigation module, perhaps proposing some edits to the documentation along the way.

**Comment by meatballs** [comment]
Sure! Go right ahead!
