### ISSUE TITLE
popup

### ISSUE THREAD

**Issue by cbhouston** [anvilistas/anvil-extras#86]
Uising the popup client code for a zoom into image type situation, its in a repeating panel. Seems the popup stays only the size/width of the current column

Attached is example
![image](https://user-images.githubusercontent.com/29504867/122451020-5044c080-cf6d-11eb-9d1f-3d31e1557125.png)

**Comment by s-cork** [comment]
can you share a clone link.

from memory - the best way to display an image is to put it in a container that knows about width


```python
content = FlowPanel(aligh='center')        # anvil components have a width property
image = Image(source=image_source, height=200, display_mode="shrink_to_fit")
content.add_component(image, width=200)
self.my_link.popover(content=content)
```

**Comment by cbhouston** [comment]
This worked........ Wish I could "Matrix Jack-in" your knowledge. Thanks.
