### ISSUE TITLE
Quill Image Resize Module

### ISSUE THREAD

**Issue by sebasm611** [anvilistas/anvil-extras#87]
Hi! Amazing and very useful tools so congrats and thanks for your work guys!!

One question.. How would I go about adding the Quill Resize module when using the extras? I managed to get it working when adding Quill by myself by adding the line below it to native libraries and making the necessary changes to the JS setup.

I tried adding the line to native libraries but it did nothing sadly as I guess I'd have to change the Quill setup on JS.

Native libraries line: `<script src="https://cdn.jsdelivr.net/npm/quill-image-resize-module@3.0.0/image-resize.min.js" async></script>`
Link to Quill image resize module: https://github.com/kensnyder/quill-image-resize-module

I don't know anything other than Python so sorry if this is easy, I just haven't found the way yet. Thanks!

**Comment by s-cork** [comment]
We'd need an interface to add custom modules at runtime.

Something like
```
self.quill.add_module(ImageResize={'displaySize': True})
```

addModules used to be part of the quill api but no longer so we'd have to implement our own thing.
How would that sound?

**Comment by sebasm611** [comment]
Sounds perfect for me!
