### ISSUE TITLE
Indeterminate Progress Bar Hit or Miss

### ISSUE THREAD

**Issue by ethanedson** [anvilistas/anvil-extras#95]
I have the new indeterminate progress bar embedded in a popup alert (an app loading screen).  I am finding that progress bar animation works maybe 50-60% of the time, where 40-50% of the time the progress bar is solid blue without the animation.  Haven't changed any code on that loading screen in a while so can't find a reason for the intermittent animation success.  Thanks for taking a look!

**Comment by hugetim** [comment]
Sure enough, I see the issue 5 out of 10 times when refreshing my demo app at https://anvil-extras-demo.anvil.app/. (I noticed it once a couple days ago when building it, but shrugged it off at the time.)

**Comment by s-cork** [comment]
I reckon you noticed this about 10 in 36 times 😉
